from typing import Any

class AccessMode: ...
class MemoryMappedMatrix: ...
def compute_fdp(*args: Any, **kwargs: Any) -> Any: ...
def compute_tpp(*args: Any, **kwargs: Any) -> Any: ...
def compute_precision(*args: Any, **kwargs: Any) -> Any: ...
def compute_recall(*args: Any, **kwargs: Any) -> Any: ...
def compute_fdp_dense(*args: Any, **kwargs: Any) -> Any: ...
def compute_tpp_dense(*args: Any, **kwargs: Any) -> Any: ...
def get_max_threads(*args: Any, **kwargs: Any) -> Any: ...
def set_num_threads(*args: Any, **kwargs: Any) -> Any: ...
