# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Rcpp Agglomerative Clustering
#'
#' @description Perform agglomerative clustering
#'
#' @param data Matrix of shape (N, Features).
#' @param method_idx Linkage method index (0=Ward, 1=Average, 2=Complete, 3=Single, 4=WPGMA,
#'                      5=Median, 6=Centroid)
#' @param metric_idx Distance metric index (0=Euclid, 1=Corr, 2=Manhattan, 3=CorrLSHF, 4=CorrLSHA)
#' @param use_mmap Boolean flag for memory mapping
#'
#' @return A linkage matrix
#'
#' @noRd
rcpp_agglomerative_cluster <- function(data, method_idx, metric_idx, use_mmap = FALSE) {
    .Call(`_TRexSelectorNeo_rcpp_agglomerative_cluster`, data, method_idx, metric_idx, use_mmap)
}

#' @title Rcpp Agglomerative Clustering (memory-mapped input)
#'
#' @description Perform agglomerative clustering on a memory-mapped input matrix.
#'              The intermediate distance storage is also disk-backed (use_mmap = true).
#'
#' @param data_ptr XPtr to a MemoryMappedMatrix<double> of shape (N, Features).
#' @param method_idx Linkage method index (0=Ward, 1=Average, 2=Complete, 3=Single, 4=WPGMA,
#'                      5=Median, 6=Centroid)
#' @param metric_idx Distance metric index (0=Euclid, 1=Corr, 2=Manhattan, 3=CorrLSHF, 4=CorrLSHA)
#'
#' @return A linkage matrix
#'
#' @noRd
rcpp_agglomerative_cluster_mmap <- function(data_ptr, method_idx, metric_idx) {
    .Call(`_TRexSelectorNeo_rcpp_agglomerative_cluster_mmap`, data_ptr, method_idx, metric_idx)
}

#' @title Rcpp Cut Tree
#'
#' @description Cut a linkage matrix into flat clusters
#'
#' @param linkage Linkage matrix from agglomerative_cluster
#' @param num_orig_objs Original number of rows in dataset
#' @param num_clusters Desired number of flat clusters
#'
#' @return Integer vector of cluster indices
#'
#' @noRd
rcpp_cut_tree <- function(linkage, num_orig_objs, num_clusters) {
    .Call(`_TRexSelectorNeo_rcpp_cut_tree`, linkage, num_orig_objs, num_clusters)
}

#' @title Create ZScoreScaler
#'
#' @param center Center columns to mean 0
#' @param scale Scale columns to unit SD (Bessel; RMS around 0 if not centered)
#' @return XPtr to ZScoreScaler
#' @noRd
zscore_scaler_create <- function(center, scale) {
    .Call(`_TRexSelectorNeo_zscore_scaler_create`, center, scale)
}

#' @title Fit ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param X Matrix to fit
#' @param threshold Numerical stability threshold
#' @noRd
zscore_scaler_fit <- function(ptr, X, threshold = 1e-12) {
    invisible(.Call(`_TRexSelectorNeo_zscore_scaler_fit`, ptr, X, threshold))
}

#' @title Transform Inplace ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param X Matrix to transform
#' @noRd
zscore_scaler_transform_inplace <- function(ptr, X) {
    invisible(.Call(`_TRexSelectorNeo_zscore_scaler_transform_inplace`, ptr, X))
}

#' @title Fit and Transform Inplace ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param X Matrix to fit and transform
#' @param threshold Numerical stability threshold
#' @noRd
zscore_scaler_fit_transform_inplace <- function(ptr, X, threshold = 1e-12) {
    invisible(.Call(`_TRexSelectorNeo_zscore_scaler_fit_transform_inplace`, ptr, X, threshold))
}

#' @title Inverse Transform Inplace ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param X Matrix to transform
#' @noRd
zscore_scaler_inverse_transform_inplace <- function(ptr, X) {
    invisible(.Call(`_TRexSelectorNeo_zscore_scaler_inverse_transform_inplace`, ptr, X))
}

#' @title Check if ZScoreScaler is fitted
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Boolean indicating fit status
#' @noRd
zscore_scaler_is_fitted <- function(ptr) {
    .Call(`_TRexSelectorNeo_zscore_scaler_is_fitted`, ptr)
}

#' @title Get dropped indices from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Vector of dropped indices
#' @noRd
zscore_scaler_get_dropped_indices <- function(ptr) {
    .Call(`_TRexSelectorNeo_zscore_scaler_get_dropped_indices`, ptr)
}

#' @title Get center flag from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Boolean center
#' @noRd
zscore_scaler_get_center <- function(ptr) {
    .Call(`_TRexSelectorNeo_zscore_scaler_get_center`, ptr)
}

#' @title Get scale flag from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Boolean scale
#' @noRd
zscore_scaler_get_scale <- function(ptr) {
    .Call(`_TRexSelectorNeo_zscore_scaler_get_scale`, ptr)
}

#' @title Get centers from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Vector of centers
#' @noRd
zscore_scaler_get_centers <- function(ptr) {
    .Call(`_TRexSelectorNeo_zscore_scaler_get_centers`, ptr)
}

#' @title Get scales from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Vector of scales
#' @noRd
zscore_scaler_get_scales <- function(ptr) {
    .Call(`_TRexSelectorNeo_zscore_scaler_get_scales`, ptr)
}

#' @title Save ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param filename Output filename
#' @noRd
zscore_scaler_save <- function(ptr, filename) {
    invisible(.Call(`_TRexSelectorNeo_zscore_scaler_save`, ptr, filename))
}

#' @title Load ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param filename Input filename
#' @noRd
zscore_scaler_load <- function(ptr, filename) {
    invisible(.Call(`_TRexSelectorNeo_zscore_scaler_load`, ptr, filename))
}

#' @title Create LpNormScaler
#'
#' @param norm_type Type of norm (1 for L1, 2 for L2)
#' @param center Center columns to mean 0
#' @param scale Scale columns to unit Lp norm (around the applied center)
#' @return XPtr to LpNormScaler
#' @noRd
lpnorm_scaler_create <- function(norm_type, center, scale) {
    .Call(`_TRexSelectorNeo_lpnorm_scaler_create`, norm_type, center, scale)
}

#' @title Fit LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param X Matrix to fit
#' @param threshold Numerical stability threshold
#' @noRd
lpnorm_scaler_fit <- function(ptr, X, threshold = 1e-12) {
    invisible(.Call(`_TRexSelectorNeo_lpnorm_scaler_fit`, ptr, X, threshold))
}

#' @title Transform Inplace LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param X Matrix to transform
#' @noRd
lpnorm_scaler_transform_inplace <- function(ptr, X) {
    invisible(.Call(`_TRexSelectorNeo_lpnorm_scaler_transform_inplace`, ptr, X))
}

#' @title Fit and Transform Inplace LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param X Matrix to fit and transform
#' @param threshold Numerical stability threshold
#' @noRd
lpnorm_scaler_fit_transform_inplace <- function(ptr, X, threshold = 1e-12) {
    invisible(.Call(`_TRexSelectorNeo_lpnorm_scaler_fit_transform_inplace`, ptr, X, threshold))
}

#' @title Inverse Transform Inplace LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param X Matrix to transform
#' @noRd
lpnorm_scaler_inverse_transform_inplace <- function(ptr, X) {
    invisible(.Call(`_TRexSelectorNeo_lpnorm_scaler_inverse_transform_inplace`, ptr, X))
}

#' @title Check if LpNormScaler is fitted
#'
#' @param ptr XPtr to LpNormScaler
#' @return Boolean indicating fit status
#' @noRd
lpnorm_scaler_is_fitted <- function(ptr) {
    .Call(`_TRexSelectorNeo_lpnorm_scaler_is_fitted`, ptr)
}

#' @title Get dropped indices from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Vector of dropped indices
#' @noRd
lpnorm_scaler_get_dropped_indices <- function(ptr) {
    .Call(`_TRexSelectorNeo_lpnorm_scaler_get_dropped_indices`, ptr)
}

#' @title Get centers from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Vector of centers
#' @noRd
lpnorm_scaler_get_centers <- function(ptr) {
    .Call(`_TRexSelectorNeo_lpnorm_scaler_get_centers`, ptr)
}

#' @title Get scales from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Vector of scales
#' @noRd
lpnorm_scaler_get_scales <- function(ptr) {
    .Call(`_TRexSelectorNeo_lpnorm_scaler_get_scales`, ptr)
}

#' @title Get center flag from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Boolean center
#' @noRd
lpnorm_scaler_get_center <- function(ptr) {
    .Call(`_TRexSelectorNeo_lpnorm_scaler_get_center`, ptr)
}

#' @title Get scale flag from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Boolean scale
#' @noRd
lpnorm_scaler_get_scale <- function(ptr) {
    .Call(`_TRexSelectorNeo_lpnorm_scaler_get_scale`, ptr)
}

#' @title Get norm type from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Integer norm type
#' @noRd
lpnorm_scaler_get_norm_type <- function(ptr) {
    .Call(`_TRexSelectorNeo_lpnorm_scaler_get_norm_type`, ptr)
}

#' @title Save LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param filename Output filename
#' @noRd
lpnorm_scaler_save <- function(ptr, filename) {
    invisible(.Call(`_TRexSelectorNeo_lpnorm_scaler_save`, ptr, filename))
}

#' @title Load LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param filename Input filename
#' @noRd
lpnorm_scaler_load <- function(ptr, filename) {
    invisible(.Call(`_TRexSelectorNeo_lpnorm_scaler_load`, ptr, filename))
}

#' @title Create Ridge CV
#'
#' @return XPtr to ridge_cv
#' @noRd
ridge_cv_create <- function() {
    .Call(`_TRexSelectorNeo_ridge_cv_create`)
}

#' @title Fit Ridge CV
#'
#' @param ptr XPtr to ridge_cv
#' @param X Design matrix
#' @param y Response vector
#' @param num_folds Number of folds
#' @param n_lambda Number of lambdas
#' @param lambda_ratio Lambda ratio
#' @param seed Random seed
#' @noRd
ridge_cv_fit <- function(ptr, X, y, num_folds, n_lambda, lambda_ratio, seed) {
    invisible(.Call(`_TRexSelectorNeo_ridge_cv_fit`, ptr, X, y, num_folds, n_lambda, lambda_ratio, seed))
}

#' @title Get min CV error
#'
#' @param ptr XPtr to ridge_cv
#' @return Min CV error
#' @noRd
ridge_cv_min <- function(ptr) {
    .Call(`_TRexSelectorNeo_ridge_cv_min`, ptr)
}

#' @title Get 1SE CV error
#'
#' @param ptr XPtr to ridge_cv
#' @return 1SE CV error
#' @noRd
ridge_cv_1se <- function(ptr) {
    .Call(`_TRexSelectorNeo_ridge_cv_1se`, ptr)
}

#' @title Get min index
#'
#' @param ptr XPtr to ridge_cv
#' @return Index of min CV error
#' @noRd
ridge_cv_index_min <- function(ptr) {
    .Call(`_TRexSelectorNeo_ridge_cv_index_min`, ptr)
}

#' @title Get 1SE index
#'
#' @param ptr XPtr to ridge_cv
#' @return Index of 1SE CV error
#' @noRd
ridge_cv_index_1se <- function(ptr) {
    .Call(`_TRexSelectorNeo_ridge_cv_index_1se`, ptr)
}

#' @title Get Lambdas
#'
#' @param ptr XPtr to ridge_cv
#' @return Vector of lambdas
#' @noRd
ridge_cv_get_lambdas <- function(ptr) {
    .Call(`_TRexSelectorNeo_ridge_cv_get_lambdas`, ptr)
}

#' @title Get CV Errors
#'
#' @param ptr XPtr to ridge_cv
#' @return Vector of CV errors
#' @noRd
ridge_cv_get_cv_errors <- function(ptr) {
    .Call(`_TRexSelectorNeo_ridge_cv_get_cv_errors`, ptr)
}

#' @title Get CV Standard Errors
#'
#' @param ptr XPtr to ridge_cv
#' @return Vector of CV standard errors
#' @noRd
ridge_cv_get_cv_std <- function(ptr) {
    .Call(`_TRexSelectorNeo_ridge_cv_get_cv_std`, ptr)
}

#' @title Create Elastic Net path
#' @return XPtr to enet_path
#' @noRd
enet_create <- function() {
    .Call(`_TRexSelectorNeo_enet_create`)
}

#' @title Fit Elastic Net over an auto-generated glmnet-style grid
#' @noRd
enet_fit <- function(ptr, X, y, alpha, n_lambda, lambda_min_ratio, standardize, intercept, use_strong_rule, max_iter, tol) {
    invisible(.Call(`_TRexSelectorNeo_enet_fit`, ptr, X, y, alpha, n_lambda, lambda_min_ratio, standardize, intercept, use_strong_rule, max_iter, tol))
}

#' @title Fit Elastic Net at an explicit lambda grid
#' @noRd
enet_fit_grid <- function(ptr, X, y, lambda_grid, alpha, standardize, intercept, use_strong_rule, max_iter, tol) {
    invisible(.Call(`_TRexSelectorNeo_enet_fit_grid`, ptr, X, y, lambda_grid, alpha, standardize, intercept, use_strong_rule, max_iter, tol))
}

#' @title Elastic Net coefficient path (p x n_lambda, original scale)
#' @noRd
enet_get_coef <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_get_coef`, ptr)
}

#' @title Elastic Net intercepts per lambda
#' @noRd
enet_get_intercepts <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_get_intercepts`, ptr)
}

#' @title Elastic Net lambda grid (descending)
#' @noRd
enet_get_lambdas <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_get_lambdas`, ptr)
}

#' @title Elastic Net deviance-ratio path (glmnet %Dev)
#' @noRd
enet_get_dev_ratio <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_get_dev_ratio`, ptr)
}

#' @title Whether every lambda converged
#' @noRd
enet_converged <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_converged`, ptr)
}

#' @title Predictions per lambda for new data
#' @noRd
enet_predict <- function(ptr, X_new) {
    .Call(`_TRexSelectorNeo_enet_predict`, ptr, X_new)
}

#' @title Create Elastic Net CV
#' @return XPtr to enet_cv
#' @noRd
enet_cv_create <- function() {
    .Call(`_TRexSelectorNeo_enet_cv_create`)
}

#' @title Fit Elastic Net CV over a glmnet-style grid
#' @noRd
enet_cv_fit <- function(ptr, X, y, alpha, n_folds, n_lambda, lambda_min_ratio, seed, standardize, intercept, max_iter, tol) {
    invisible(.Call(`_TRexSelectorNeo_enet_cv_fit`, ptr, X, y, alpha, n_folds, n_lambda, lambda_min_ratio, seed, standardize, intercept, max_iter, tol))
}

#' @title Elastic Net CV lambda.min
#' @noRd
enet_cv_min <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_cv_min`, ptr)
}

#' @title Elastic Net CV lambda.1se
#' @noRd
enet_cv_1se <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_cv_1se`, ptr)
}

#' @title Elastic Net CV index of lambda.min (0-based)
#' @noRd
enet_cv_index_min <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_cv_index_min`, ptr)
}

#' @title Elastic Net CV index of lambda.1se (0-based)
#' @noRd
enet_cv_index_1se <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_cv_index_1se`, ptr)
}

#' @title Elastic Net CV lambda grid (descending)
#' @noRd
enet_cv_get_lambdas <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_cv_get_lambdas`, ptr)
}

#' @title Elastic Net CV mean MSE per lambda
#' @noRd
enet_cv_get_cv_errors <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_cv_get_cv_errors`, ptr)
}

#' @title Elastic Net CV standard error per lambda
#' @noRd
enet_cv_get_cv_std <- function(ptr) {
    .Call(`_TRexSelectorNeo_enet_cv_get_cv_std`, ptr)
}

#' @title Compute SVD
#'
#' @description Computes the top-M SVD of a matrix, dispatching between direct,
#'   Gram, and randomized paths based on matrix shape.
#'
#' @param X Numeric matrix (n x p).
#' @param M Integer, number of singular components to compute.
#'
#' @return Named list with elements \code{U} (n x M), \code{S} (M),
#'   and \code{V} (p x M).
#' @noRd
svd_compute <- function(X, M) {
    .Call(`_TRexSelectorNeo_svd_compute`, X, M)
}

#' @title Create PCA object
#'
#' @description Constructs a PCA instance bound to \code{X}. Centering and/or
#'   normalization are applied to \code{X} in-place immediately; call
#'   \code{pca_restore()} with the same matrix to undo them.
#'
#' @param X Numeric matrix (n x p). Modified in-place when center/normalize.
#' @param M Integer number of principal components.
#' @param center Logical, whether to center X in-place.
#' @param normalize Logical, whether to scale X columns in-place.
#'
#' @return XPtr to a PCA instance.
#' @noRd
pca_create <- function(X, M, center = TRUE, normalize = TRUE) {
    .Call(`_TRexSelectorNeo_pca_create`, X, M, center, normalize)
}

#' @title Fit PCA
#'
#' @description Fits the PCA bound at creation time; single-use per instance.
#'
#' @param ptr XPtr to PCA.
#'
#' @return Named list with \code{Z} (n x M scores), \code{V} (p x M loadings),
#'   and \code{explained_variance} (M-vector).
#' @noRd
pca_fit <- function(ptr) {
    .Call(`_TRexSelectorNeo_pca_fit`, ptr)
}

#' @title Restore X after PCA centering/normalization
#'
#' @param ptr XPtr to PCA.
#' @param X The same matrix that was passed to \code{pca_create()}.
#' @noRd
pca_restore <- function(ptr, X) {
    invisible(.Call(`_TRexSelectorNeo_pca_restore`, ptr, X))
}

#' @title Transform new data with fitted PCA
#'
#' @param ptr XPtr to PCA.
#' @param X_new Numeric matrix (n_new x p).
#'
#' @return Score matrix (n_new x M).
#' @noRd
pca_transform <- function(ptr, X_new) {
    .Call(`_TRexSelectorNeo_pca_transform`, ptr, X_new)
}

#' @title Get PCA column means
#'
#' @param ptr XPtr to PCA.
#' @return Vector of column means (zero-vector when center = FALSE).
#' @noRd
pca_get_means <- function(ptr) {
    .Call(`_TRexSelectorNeo_pca_get_means`, ptr)
}

#' @title Get PCA column norms
#'
#' @param ptr XPtr to PCA.
#' @return Vector of column scaling factors (ones when normalize = FALSE).
#' @noRd
pca_get_norms <- function(ptr) {
    .Call(`_TRexSelectorNeo_pca_get_norms`, ptr)
}

#' @title Get PCA loadings
#'
#' @param ptr XPtr to PCA.
#' @return Loading matrix (p x M).
#' @noRd
pca_get_loadings <- function(ptr) {
    .Call(`_TRexSelectorNeo_pca_get_loadings`, ptr)
}

#' @title Get PCA explained variance
#'
#' @param ptr XPtr to PCA.
#' @return Numeric vector of explained variance per component.
#' @noRd
pca_get_explained_variance <- function(ptr) {
    .Call(`_TRexSelectorNeo_pca_get_explained_variance`, ptr)
}

#' @title Solve Ridge Regression
#'
#' @description Solves \eqn{\min \|y - X\beta\|^2 + \lambda\|\beta\|^2} for a
#'   single regularization value, dispatching between primal (n >= p) and dual
#'   (n < p) Cholesky solvers automatically.
#'
#' @param X Numeric matrix (n x p).
#' @param y Numeric response vector (n).
#' @param lambda Non-negative regularization parameter.
#'
#' @return Coefficient vector of length p.
#' @noRd
ridge_solve <- function(X, y, lambda) {
    .Call(`_TRexSelectorNeo_ridge_solve`, X, y, lambda)
}

#' @title Create RTRexBiobankScreeningSelector 1D
#' @noRd
trex_biobank_screening_1d_create <- function(X, y, biobank_control_list, screen_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelectorNeo_trex_biobank_screening_1d_create`, X, y, biobank_control_list, screen_control_list, trex_control_list, seed, verbose)
}

#' @title Create RTRexBiobankScreeningSelector 2D
#' @noRd
trex_biobank_screening_2d_create <- function(X, Y, biobank_control_list, screen_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelectorNeo_trex_biobank_screening_2d_create`, X, Y, biobank_control_list, screen_control_list, trex_control_list, seed, verbose)
}

#' @title Screen Single Phenotype
#' @noRd
trex_biobank_screening_screen_phenotype <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_biobank_screening_screen_phenotype`, r_ptr)
}

#' @title Screen Multiple Phenotypes
#' @noRd
trex_biobank_screening_screen_phenotypes <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_biobank_screening_screen_phenotypes`, r_ptr)
}

#' @title Create TRexDASelector
#' @noRd
trex_da_create <- function(X, y, tFDR, da_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelectorNeo_trex_da_create`, X, y, tFDR, da_control_list, trex_control_list, seed, verbose)
}

#' @title Create TRexDASelector from mmap
#' @noRd
trex_da_mmap_create <- function(X_ptr, y, tFDR, da_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelectorNeo_trex_da_mmap_create`, X_ptr, y, tFDR, da_control_list, trex_control_list, seed, verbose)
}

#' @title Run TRexDASelector
#' @noRd
trex_da_select <- function(r_ptr) {
    invisible(.Call(`_TRexSelectorNeo_trex_da_select`, r_ptr))
}

#' @title Cast DA pointer to Base pointer
#' @noRd
trex_da_to_base_ptr <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_da_to_base_ptr`, r_ptr)
}

#' @title Get DA Rho Threshold
#' @noRd
trex_da_get_rho_thresh <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_da_get_rho_thresh`, r_ptr)
}

#' @title Get DA Rho Grid
#' @noRd
trex_da_get_rho_grid <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_da_get_rho_grid`, r_ptr)
}

#' @title Get DA Method String
#' @noRd
trex_da_get_method_string <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_da_get_method_string`, r_ptr)
}

#' @title Get DA Cor Coef
#' @noRd
trex_da_get_cor_coef <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_da_get_cor_coef`, r_ptr)
}

#' @title Get DA FDP Hat Array BT
#' @noRd
trex_da_get_fdp_hat_array_bt <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_da_get_fdp_hat_array_bt`, r_ptr)
}

#' @title Get DA Phi Array BT
#' @noRd
trex_da_get_phi_array_bt <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_da_get_phi_array_bt`, r_ptr)
}

#' @title Get DA R Array BT
#' @noRd
trex_da_get_r_array_bt <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_da_get_r_array_bt`, r_ptr)
}

#' @title Create TRexGVSSelector
#' @noRd
trex_gvs_create <- function(X, y, tFDR, gvs_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelectorNeo_trex_gvs_create`, X, y, tFDR, gvs_control_list, trex_control_list, seed, verbose)
}

#' @title Create TRexGVSSelector from MemoryMappedMatrix
#' @noRd
trex_gvs_mmap_create <- function(X_ptr, y, tFDR, gvs_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelectorNeo_trex_gvs_mmap_create`, X_ptr, y, tFDR, gvs_control_list, trex_control_list, seed, verbose)
}

#' @title Run TRexGVSSelector
#' @noRd
trex_gvs_select <- function(r_ptr) {
    invisible(.Call(`_TRexSelectorNeo_trex_gvs_select`, r_ptr))
}

#' @title Get lambda2_used
#' @noRd
trex_gvs_get_lambda2_used <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_gvs_get_lambda2_used`, r_ptr)
}

#' @title Get gvs_type
#' @noRd
trex_gvs_get_gvs_type <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_gvs_get_gvs_type`, r_ptr)
}

#' @title Get max_clusters
#' @noRd
trex_gvs_get_max_clusters <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_gvs_get_max_clusters`, r_ptr)
}

#' @title Get Selected Indices
#' @noRd
trex_gvs_get_selected_indices <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_gvs_get_selected_indices`, r_ptr)
}

#' @title Create RTRexScreeningSelector
#'
#' @details Instantiates a Screen-TRex selector object.
#'
#' @param X Design matrix (n x p).
#' @param y Response vector (n).
#' @param screen_control_list List of Screen-TRex specific control parameters.
#' @param trex_control_list List of general T-Rex control parameters.
#' @param seed Random seed for reproducibility.
#' @param verbose Whether to print progress messages.
#'
#' @return XPtr to RTRexScreeningSelector instance.
#'
#' @noRd
#'
trex_screening_create <- function(X, y, screen_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelectorNeo_trex_screening_create`, X, y, screen_control_list, trex_control_list, seed, verbose)
}

#' @title Create RTRexScreeningSelector from mmap
#'
#' @details Instantiates a Screen-TRex selector object using a memory-mapped design matrix
#'
#' @param X_ptr Pointer to MemoryMappedMatrix for the design matrix.
#' @param y Response vector (n).
#' @param screen_control_list List of Screen-TRex specific control parameters.
#' @param trex_control_list List of general T-Rex control parameters.
#' @param seed Random seed for reproducibility.
#' @param verbose Whether to print progress messages.
#'
#' @noRd
#'
trex_screening_mmap_create <- function(X_ptr, y, screen_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelectorNeo_trex_screening_mmap_create`, X_ptr, y, screen_control_list, trex_control_list, seed, verbose)
}

#' @title Run RTRexScreeningSelector
#'
#' @details Executes the selection procedure of the Screen-TRex selector.
#'
#' @param r_ptr Pointer to the RTRexScreeningSelector instance
#'
#' @noRd
#'
trex_screening_select <- function(r_ptr) {
    invisible(.Call(`_TRexSelectorNeo_trex_screening_select`, r_ptr))
}

#' @title Get estimated_FDR
#' @noRd
trex_screening_get_estimated_fdr <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_screening_get_estimated_fdr`, r_ptr)
}

#' @title Get used_bootstrap
#' @noRd
trex_screening_get_used_bootstrap <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_screening_get_used_bootstrap`, r_ptr)
}

#' @title Get confidence_level
#' @noRd
trex_screening_get_confidence_level <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_screening_get_confidence_level`, r_ptr)
}

#' @title Get estimated_correlation
#' @noRd
trex_screening_get_estimated_correlation <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_screening_get_estimated_correlation`, r_ptr)
}

#' @title Get beta_mat
#' @noRd
trex_screening_get_beta_mat <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_screening_get_beta_mat`, r_ptr)
}

#' @title Get dummy_betas
#' @noRd
trex_screening_get_dummy_betas <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_screening_get_dummy_betas`, r_ptr)
}

#' @title Get Selected Indices
#'
#' @details Retrieves the indices of the selected variables from the Screen-TRex selector.
#'
#' @param r_ptr Pointer to the RTRexScreeningSelector instance.
#'
#' @noRd
#'
trex_screening_get_selected_indices <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_screening_get_selected_indices`, r_ptr)
}

#' @title Create TRexSelector
#'
#' @param X Design matrix (n × p).
#' @param y Response vector (n).
#' @param tFDR Target FDR level (default: 0.1).
#' @param control List of control parameters (see details).
#' @param seed Random seed (default: -1).
#' @param verbose Whether to print progress (default: TRUE).
#'
#' @noRd
trex_selector_create <- function(X, y, tFDR, control_list, seed, verbose) {
    .Call(`_TRexSelectorNeo_trex_selector_create`, X, y, tFDR, control_list, seed, verbose)
}

#' @title Create TRexSelector from mmap
#'
#' @param X_ptr Pointer to MemoryMappedMatrix (n × p).
#' @param y Response vector (n).
#' @param tFDR Target FDR level (default: 0.1).
#' @param control List of control parameters (see details).
#' @param seed Random seed (default: -1).
#' @param verbose Whether to print progress (default: TRUE).
#'
#' @noRd
trex_selector_mmap_create <- function(X_ptr, y, tFDR, control_list, seed, verbose) {
    .Call(`_TRexSelectorNeo_trex_selector_mmap_create`, X_ptr, y, tFDR, control_list, seed, verbose)
}

#' @title Run TRexSelector
#'
#' @param r_ptr Pointer to RTRexSelector instance.
#'
#' @noRd
trex_selector_select <- function(r_ptr) {
    invisible(.Call(`_TRexSelectorNeo_trex_selector_select`, r_ptr))
}

#' @title Get Selected Variables
#'
#' @param r_ptr Pointer to RTRexSelector instance.
#'
#' @noRd
trex_selector_get_selected_var <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_selected_var`, r_ptr)
}

#' @title Get Selected Indices
#'
#' @param r_ptr Pointer to RTRexSelector instance.
#'
#' @noRd
trex_selector_get_selected_indices <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_selected_indices`, r_ptr)
}

#' @title Get Voting Threshold
#' @noRd
trex_selector_get_voting_threshold <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_voting_threshold`, r_ptr)
}

#' @title Get Stopping Time T
#' @noRd
trex_selector_get_t_stop <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_t_stop`, r_ptr)
}

#' @title Get Dummy Multiplier L
#' @noRd
trex_selector_get_dummy_multiplier_l <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_dummy_multiplier_l`, r_ptr)
}

#' @title Get Voting Grid
#' @noRd
trex_selector_get_voting_grid <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_voting_grid`, r_ptr)
}

#' @title Get FDP Hat Matrix
#' @noRd
trex_selector_get_fdp_hat_mat <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_fdp_hat_mat`, r_ptr)
}

#' @title Get Phi Matrix
#' @noRd
trex_selector_get_phi_mat <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_phi_mat`, r_ptr)
}

#' @title Get R Matrix
#' @noRd
trex_selector_get_r_mat <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_r_mat`, r_ptr)
}

#' @title Get Phi Prime
#' @noRd
trex_selector_get_phi_prime <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_phi_prime`, r_ptr)
}

#' @title Get X Means
#' @noRd
trex_selector_get_x_means <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_x_means`, r_ptr)
}

#' @title Get X L2 Norms
#' @noRd
trex_selector_get_x_l2_norms <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_x_l2_norms`, r_ptr)
}

#' @title Get y Mean
#' @noRd
trex_selector_get_y_mean <- function(r_ptr) {
    .Call(`_TRexSelectorNeo_trex_selector_get_y_mean`, r_ptr)
}

#' @title Run T-Rex Sparse PCA selection
#'
#' @description Orchestrates M rounds of ordinary PCA, T-Rex GVS FDR-controlled
#'   variable selection, and sparse loading assembly to produce sparse principal
#'   components.
#'
#' @param X Design matrix (n x p). Column-centered internally; restored on return.
#' @param M Integer, number of sparse PCs to extract.
#' @param tFDR Numeric, target false discovery rate in (0, 1).
#' @param spca_ctrl_list Named R list of control parameters (mode,
#'   lambda2_ridge_loadings, gvs_type, lambda_2, lambda2_method,
#'   K, max_dummy_multiplier).
#' @param seed Integer random seed. \code{-1} (default) for non-deterministic.
#'
#' @return Named list:
#'   \itemize{
#'     \item \code{Z} Score matrix (n x M).
#'     \item \code{V} Loading matrix (p x M).
#'     \item \code{active_sets} List of M integer vectors (1-based indices).
#'     \item \code{adjusted_ev} Numeric vector of adjusted explained variance (M).
#'     \item \code{cumulative_ev} Numeric vector of cumulative explained variance (M).
#'   }
#' @noRd
trex_spca_select <- function(X, M, tFDR, spca_ctrl_list, seed, verbose) {
    .Call(`_TRexSelectorNeo_trex_spca_select`, X, M, tFDR, spca_ctrl_list, seed, verbose)
}

#' @title Create LARS Solver
#'
#' @param X Design matrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolverRcpp
#' @noRd
tsolver_lars_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_lars_create`, X, D, y, normalize, intercept, verbose)
}

#' @title Create OMP Solver
#'
#' @param X Design matrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolverRcpp
#' @noRd
tsolver_omp_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_omp_create`, X, D, y, normalize, intercept, verbose)
}

#' @title Create LARS Solver with Memory Mapped Matrix
#'
#' @param X_ptr Pointer to MemoryMappedMatrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolverRcpp
#' @noRd
tsolver_lars_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_lars_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @title Create OMP Solver with Memory Mapped Matrix
#'
#' @param X_ptr Pointer to MemoryMappedMatrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolverRcpp
#' @noRd
tsolver_omp_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_omp_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tlasso_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tlasso_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tstepwise_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tstepwise_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tenet_create <- function(X, D, y, lambda2, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tenet_create`, X, D, y, lambda2, normalize, intercept, verbose)
}

#' @noRd
tsolver_tenet_aug_create <- function(X, D, y, lambda2, normalize = TRUE, intercept = TRUE, verbose = FALSE, use_lars_inner = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tenet_aug_create`, X, D, y, lambda2, normalize, intercept, verbose, use_lars_inner)
}

#' @noRd
tsolver_tienet_aug_create <- function(X, D, y, lambda2, groups, normalize = TRUE, intercept = TRUE, verbose = FALSE, use_lars_inner = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tienet_aug_create`, X, D, y, lambda2, groups, normalize, intercept, verbose, use_lars_inner)
}

#' @noRd
tsolver_tstagewise_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tstagewise_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tgp_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tgp_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tacgp_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tacgp_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tmp_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tmp_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tools_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tools_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tncgmp_create <- function(X, D, y, variant = 0L, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tncgmp_create`, X, D, y, variant, normalize, intercept, verbose)
}

#' @noRd
tsolver_tafs_create <- function(X, D, y, rho = 1.0, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tafs_create`, X, D, y, rho, normalize, intercept, verbose)
}

#' @noRd
tsolver_tlasso_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tlasso_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tstepwise_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tstepwise_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tenet_mmap_create <- function(X_ptr, D, y, lambda2, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tenet_mmap_create`, X_ptr, D, y, lambda2, normalize, intercept, verbose)
}

#' @noRd
tsolver_tenet_aug_mmap_create <- function(X_ptr, D, y, lambda2, normalize = TRUE, intercept = TRUE, verbose = FALSE, use_lars_inner = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tenet_aug_mmap_create`, X_ptr, D, y, lambda2, normalize, intercept, verbose, use_lars_inner)
}

#' @noRd
tsolver_tienet_aug_mmap_create <- function(X_ptr, D, y, lambda2, groups, normalize = TRUE, intercept = TRUE, verbose = FALSE, use_lars_inner = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tienet_aug_mmap_create`, X_ptr, D, y, lambda2, groups, normalize, intercept, verbose, use_lars_inner)
}

#' @noRd
tsolver_tstagewise_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tstagewise_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tgp_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tgp_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tacgp_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tacgp_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tmp_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tmp_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tools_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tools_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tncgmp_mmap_create <- function(X_ptr, D, y, variant = 0L, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tncgmp_mmap_create`, X_ptr, D, y, variant, normalize, intercept, verbose)
}

#' @noRd
tsolver_tafs_mmap_create <- function(X_ptr, D, y, rho = 1.0, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelectorNeo_tsolver_tafs_mmap_create`, X_ptr, D, y, rho, normalize, intercept, verbose)
}

#' @title Execute Step in TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @param T_stop Number of steps to compute
#' @param early_stop Whether to stop early based on constraints
#' @noRd
tsolver_execute_step <- function(ptr, T_stop, early_stop = TRUE) {
    invisible(.Call(`_TRexSelectorNeo_tsolver_execute_step`, ptr, T_stop, early_stop))
}

#' @title Get Beta from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @param step Step to retrieve beta for
#'
#' @return Beta vector
#' @noRd
tsolver_get_beta <- function(ptr, step = -1L) {
    .Call(`_TRexSelectorNeo_tsolver_get_beta`, ptr, step)
}

#' @title Get Cp scores from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of Cp scores
#' @noRd
tsolver_get_cp <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_get_cp`, ptr)
}

#' @title Get RSS from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of RSS scores
#' @noRd
tsolver_get_rss <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_get_rss`, ptr)
}

#' @title Get R2 from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of R2 scores
#' @noRd
tsolver_get_r2 <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_get_r2`, ptr)
}

#' @title Get Degrees of Freedom from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of DoF
#' @noRd
tsolver_get_dof <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_get_dof`, ptr)
}

#' @title Get Active Set from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of active variable indices
#' @noRd
tsolver_get_actives <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_get_actives`, ptr)
}

#' @title Get Inactive Set from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of inactive variable indices
#' @noRd
tsolver_get_inactives <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_get_inactives`, ptr)
}

#' @title Get Intercept from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @param step Step to retrieve the intercept for
#' @return Numeric intercept value
#' @noRd
tsolver_get_intercept <- function(ptr, step = -1L) {
    .Call(`_TRexSelectorNeo_tsolver_get_intercept`, ptr, step)
}

#' @noRd
tsolver_get_num_steps <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_get_num_steps`, ptr)
}

#' @noRd
tsolver_get_actions <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_get_actions`, ptr)
}

#' @noRd
tsolver_get_lambda <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_get_lambda`, ptr)
}

#' @noRd
tsolver_get_num_removals <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_get_num_removals`, ptr)
}

#' @noRd
tsolver_get_cycling_ratio <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_get_cycling_ratio`, ptr)
}

#' @noRd
tsolver_tienet_aug_get_lambda2 <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_tienet_aug_get_lambda2`, ptr)
}

#' @noRd
tsolver_tienet_aug_get_groups <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_tienet_aug_get_groups`, ptr)
}

#' @noRd
tsolver_tienet_aug_get_num_groups <- function(ptr) {
    .Call(`_TRexSelectorNeo_tsolver_tienet_aug_get_num_groups`, ptr)
}

#' @title Save TSolver to File
#'
#' @param ptr TSolverRcpp holder pointer
#' @param filename Output filename
#' @noRd
tsolver_save <- function(ptr, filename) {
    invisible(.Call(`_TRexSelectorNeo_tsolver_save`, ptr, filename))
}

#' @title Load TSolver from File
#'
#' @param ptr TSolverRcpp holder pointer
#' @param filename Input filename
#' @noRd
tsolver_load <- function(ptr, filename) {
    invisible(.Call(`_TRexSelectorNeo_tsolver_load`, ptr, filename))
}

#' @title Set custom temp directory for the C++ backend
#'
#' @description Injects the R session's tempdir() into the C++ backend to obey CRAN memory rules.
#'
#' @param temp_dir The absolute path to the directory (e.g. from `tempdir()`).
#'
#' @noRd
rcpp_set_custom_temp_dir <- function(temp_dir) {
    invisible(.Call(`_TRexSelectorNeo_rcpp_set_custom_temp_dir`, temp_dir))
}

#' @title Create Memory Mapped Matrix
#'
#' @param filename Path to the file.
#' @param rows Number of rows
#' @param cols Number of columns.
#' @param mode_idx Mode index with 0: ReadOnly, 1: ReadWrite.
#'
#' @return XPtr to MemoryMappedMatrix
#'
#' @noRd
mmap_matrix_create <- function(filename, rows, cols, mode_idx = 1L) {
    .Call(`_TRexSelectorNeo_mmap_matrix_create`, filename, rows, cols, mode_idx)
}

#' @title Convert Memory Mapped Matrix to R Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#'
#' @return NumericMatrix
#'
#' @noRd
mmap_matrix_to_r_matrix <- function(ptr) {
    .Call(`_TRexSelectorNeo_mmap_matrix_to_r_matrix`, ptr)
}

#' @title Convert R Matrix to Memory Mapped Matrix
#'
#' @param mat R NumericMatrix
#' @param filename Output filename
#'
#' @noRd
convert_to_memory_mapped_matrix <- function(mat, filename) {
    invisible(.Call(`_TRexSelectorNeo_convert_to_memory_mapped_matrix`, mat, filename))
}

#' @title Get Number of Rows in Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#'
#' @return Integer number of rows
#'
#' @noRd
mmap_matrix_rows <- function(ptr) {
    .Call(`_TRexSelectorNeo_mmap_matrix_rows`, ptr)
}

#' @title Get Number of Columns in Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @return Integer number of columns
#'
#' @noRd
mmap_matrix_cols <- function(ptr) {
    .Call(`_TRexSelectorNeo_mmap_matrix_cols`, ptr)
}

#' @title Get Total Size of Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#'
#' @return Integer total size
#'
#' @noRd
mmap_matrix_size <- function(ptr) {
    .Call(`_TRexSelectorNeo_mmap_matrix_size`, ptr)
}

#' @title Read Block from Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @param row_start Start row index (0-based)
#' @param row_count Number of rows to read
#' @param col_start Start column index (0-based)
#' @param col_count Number of columns to read
#'
#' @return NumericMatrix block
#'
#' @noRd
mmap_matrix_read_range <- function(ptr, row_start, row_count, col_start, col_count) {
    .Call(`_TRexSelectorNeo_mmap_matrix_read_range`, ptr, row_start, row_count, col_start, col_count)
}

#' @title Get Single Element from Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @param row Row index (0-based)
#' @param col Column index (0-based)
#'
#' @return Scalar double value
#'
#' @noRd
mmap_matrix_get_element <- function(ptr, row, col) {
    .Call(`_TRexSelectorNeo_mmap_matrix_get_element`, ptr, row, col)
}

#' @title Set Single Element in Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @param row Row index (0-based)
#' @param col Column index (0-based)
#' @param value Value to write
#'
#' @noRd
mmap_matrix_set_element <- function(ptr, row, col, value) {
    invisible(.Call(`_TRexSelectorNeo_mmap_matrix_set_element`, ptr, row, col, value))
}

#' @title Write Block to Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @param row_start Start row index (0-based)
#' @param row_count Number of rows
#' @param col_start Start column index (0-based)
#' @param col_count Number of columns
#' @param values NumericMatrix with values to write
#'
#' @noRd
mmap_matrix_write_range <- function(ptr, row_start, row_count, col_start, col_count, values) {
    invisible(.Call(`_TRexSelectorNeo_mmap_matrix_write_range`, ptr, row_start, row_count, col_start, col_count, values))
}

#' @title Compute FDP from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#'
#' @return FDP value
#'
#' @noRd
rcpp_compute_fdp <- function(selected_indices, true_support) {
    .Call(`_TRexSelectorNeo_rcpp_compute_fdp`, selected_indices, true_support)
}

#' @title Compute TPP from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#'
#' @return TPP value
#'
#' @noRd
rcpp_compute_tpp <- function(selected_indices, true_support) {
    .Call(`_TRexSelectorNeo_rcpp_compute_tpp`, selected_indices, true_support)
}

#' @title Compute Precision from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#'
#' @return Precision value
#'
#' @noRd
rcpp_compute_precision <- function(selected_indices, true_support) {
    .Call(`_TRexSelectorNeo_rcpp_compute_precision`, selected_indices, true_support)
}

#' @title Compute Recall from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#'
#' @return Recall value
#'
#' @noRd
rcpp_compute_recall <- function(selected_indices, true_support) {
    .Call(`_TRexSelectorNeo_rcpp_compute_recall`, selected_indices, true_support)
}

#' @title Compute FDP from dense vectors
#'
#' @param beta_hat Estimated coefficients.
#' @param beta True coefficients.
#' @param eps Tolerance.
#'
#' @return FDP value
#'
#' @noRd
rcpp_compute_fdp_dense <- function(beta_hat, beta, eps = 1e-15) {
    .Call(`_TRexSelectorNeo_rcpp_compute_fdp_dense`, beta_hat, beta, eps)
}

#' @title Compute TPP from dense vectors
#'
#' @param beta_hat Estimated coefficients.
#' @param beta True coefficients.
#' @param eps Tolerance.
#'
#' @return TPP value.
#'
#' @noRd
rcpp_compute_tpp_dense <- function(beta_hat, beta, eps = 1e-15) {
    .Call(`_TRexSelectorNeo_rcpp_compute_tpp_dense`, beta_hat, beta, eps)
}

