#!/bin/bash
set -euo pipefail
# =============================================================================
# bundle_for_cran.sh — vendor the C++ backend into the R package.
#
# CRAN tarballs must be self-contained, so the canonical C++ sources under
# cpp/src/ are copied into src/ here. Run this script whenever the C++ core
# changes, before R CMD build.
#
# It only (re)generates the vendored subtrees and the OBJECTS list inside
# src/Makevars.in and src/Makevars.win. Compiler flags in those templates are
# CRAN-compliant: no -O overrides, no absolute local paths (OpenMP is resolved
# by configure on unix and SHLIB_OPENMP_CXXFLAGS on Windows).
#
# The vendored copies are committed to git so every commit records the exact
# C++ state the package was built against. `--check` verifies (content-based,
# no writes) that they have not silently diverged from cpp/src — run it in CI
# or before a release; it exits non-zero and lists the differences if stale.
# =============================================================================

# Always run relative to the package root (R/TRexSelectorNeo/, one level
# above this script), regardless of where it is invoked from.
cd "$(dirname "$0")/.."

CPP_SRC="../../cpp/src"
SUBTREES=(ml_methods trex_selector_methods tsolvers utils)

if [ ! -d "$CPP_SRC" ]; then
    echo "ERROR: $CPP_SRC not found — expected the C++ tree under cpp/src/." >&2
    exit 1
fi

RSYNC_EXCLUDES=(
    --exclude 'CMakeLists.txt'
    --exclude '*demo*'
    --exclude 'main.cpp'
    --exclude '*.o'
    --exclude '*.so'
)

# Regenerate the OBJECTS list from the .cpp files under a src directory.
# R does not recurse into src subdirectories, so every .cpp must be listed
# explicitly (CRAN discourages GNU-make wildcards).
list_objects() {
    (cd "$1" && find . -type f -name '*.cpp' | sed 's|^\./||; s|\.cpp$|.o|' | sort | tr '\n' ' ')
}

if [ "${1:-}" = "--check" ]; then
    echo "=== Checking vendored copies against $CPP_SRC (content-based) ==="
    status=0
    for tree in "${SUBTREES[@]}"; do
        # -rlc compares content only (checksum; no perms/mtimes, which git
        # does not preserve); itemized output is non-empty iff files differ,
        # are missing, or would be deleted.
        diff_out=$(rsync -rlci --delete --dry-run "${RSYNC_EXCLUDES[@]}" \
            "$CPP_SRC/$tree/" "src/$tree/")
        if [ -n "$diff_out" ]; then
            echo "DIVERGED: src/$tree/"
            echo "$diff_out" | sed 's/^/    /'
            status=1
        fi
    done
    expected_objects=$(list_objects src)
    for mv in src/Makevars.in src/Makevars.win; do
        current_objects=$(grep '^OBJECTS = ' "$mv" | sed 's/^OBJECTS = //')
        if [ "$current_objects" != "$expected_objects" ]; then
            echo "DIVERGED: OBJECTS list in $mv is stale."
            status=1
        fi
    done
    if [ $status -eq 0 ]; then
        echo "OK: vendored sources and OBJECTS lists match cpp/src."
    else
        echo "Run $0 (no args) to refresh, then commit the changes." >&2
    fi
    exit $status
fi

echo "=== Vendoring C++ backend from $CPP_SRC ==="
for tree in "${SUBTREES[@]}"; do
    rsync -a --delete "${RSYNC_EXCLUDES[@]}" "$CPP_SRC/$tree/" "src/$tree/"
done

echo "=== Regenerating OBJECTS list ==="
CPP_OBJECTS=$(list_objects src)

write_makevars() {
    local file="$1" cxxflags="$2" libs="$3"
    cat > "$file" << EOF
# Generated by bundle_for_cran.sh — edit the templates there, not this file.
CXX_STD = CXX20
PKG_CPPFLAGS = -I. -DCRAN_BUILD=1
PKG_CXXFLAGS = $cxxflags
PKG_LIBS = $libs \$(LAPACK_LIBS) \$(BLAS_LIBS) \$(FLIBS)
OBJECTS = $CPP_OBJECTS
EOF
}

# unix: configure substitutes the OpenMP flags and produces src/Makevars
write_makevars src/Makevars.in  '@OPENMP_CXXFLAGS@'        '@OPENMP_LIBS@'
# Windows: Rtools provides OpenMP via SHLIB_OPENMP_CXXFLAGS
write_makevars src/Makevars.win '$(SHLIB_OPENMP_CXXFLAGS)' '$(SHLIB_OPENMP_CXXFLAGS)'

echo "Vendored $(find src -name '*.cpp' | wc -l | tr -d ' ') .cpp files."
echo "Ready for Rcpp::compileAttributes() and R CMD build."
