import numpy as np

# ---------------------------------------------------------------------------
# NCGMPVariant
# ---------------------------------------------------------------------------

class NCGMPVariant:
    LineSearch: NCGMPVariant
    FullyCorrective: NCGMPVariant

# ---------------------------------------------------------------------------
# TOMP_Solver
# ---------------------------------------------------------------------------

class TOMP_Solver:
    def __init__(
        self,
        X: np.ndarray,
        D: np.ndarray,
        y: np.ndarray,
        normalize: bool = ...,
        intercept: bool = ...,
        verbose: bool = ...,
    ) -> None: ...
    def executeStep(self, T_stop: int = ..., early_stop: bool = ...) -> None: ...
    def getBeta(self, step: int = ...) -> np.ndarray: ...
    def getIntercept(self, step: int = ...) -> float: ...
    def getBetaPath(self) -> np.ndarray: ...
    def solverTypeToString(self) -> str: ...
    def getCp(self) -> list[float]: ...
    def getCpWithSigma(self, sigma_hat_sq: float) -> list[float]: ...
    def getRSS(self) -> list[float]: ...
    def getR2(self) -> list[float]: ...
    def getDoF(self) -> list[int]: ...
    def getResiduals(self) -> np.ndarray: ...
    def getActions(self) -> list[list[int]]: ...
    def getActives(self) -> list[int]: ...
    def getInactives(self) -> list[int]: ...
    def getDroppedIndices(self) -> list[int]: ...
    def getNumActives(self) -> int: ...
    def getDummyStartIndex(self) -> int: ...
    def getNumSteps(self) -> int: ...
    def isConnected(self) -> bool: ...
    def reconnect(self, X: np.ndarray, D: np.ndarray) -> None: ...
    def restore(self, X: np.ndarray, D: np.ndarray, y: np.ndarray) -> None: ...
    def save(self, filepath: str) -> None: ...
    def load(self, filepath: str) -> None: ...

# ---------------------------------------------------------------------------
# TGP_Solver
# ---------------------------------------------------------------------------

class TGP_Solver:
    def __init__(
        self,
        X: np.ndarray,
        D: np.ndarray,
        y: np.ndarray,
        normalize: bool = ...,
        intercept: bool = ...,
        verbose: bool = ...,
    ) -> None: ...
    def executeStep(self, T_stop: int = ..., early_stop: bool = ...) -> None: ...
    def getBeta(self, step: int = ...) -> np.ndarray: ...
    def getIntercept(self, step: int = ...) -> float: ...
    def getBetaPath(self) -> np.ndarray: ...
    def solverTypeToString(self) -> str: ...
    def getCp(self) -> list[float]: ...
    def getCpWithSigma(self, sigma_hat_sq: float) -> list[float]: ...
    def getRSS(self) -> list[float]: ...
    def getR2(self) -> list[float]: ...
    def getDoF(self) -> list[int]: ...
    def getResiduals(self) -> np.ndarray: ...
    def getActions(self) -> list[list[int]]: ...
    def getActives(self) -> list[int]: ...
    def getInactives(self) -> list[int]: ...
    def getDroppedIndices(self) -> list[int]: ...
    def getNumActives(self) -> int: ...
    def getDummyStartIndex(self) -> int: ...
    def getNumSteps(self) -> int: ...
    def isConnected(self) -> bool: ...
    def reconnect(self, X: np.ndarray, D: np.ndarray) -> None: ...
    def restore(self, X: np.ndarray, D: np.ndarray, y: np.ndarray) -> None: ...
    def save(self, filepath: str) -> None: ...
    def load(self, filepath: str) -> None: ...

# ---------------------------------------------------------------------------
# TACGP_Solver
# ---------------------------------------------------------------------------

class TACGP_Solver:
    def __init__(
        self,
        X: np.ndarray,
        D: np.ndarray,
        y: np.ndarray,
        normalize: bool = ...,
        intercept: bool = ...,
        verbose: bool = ...,
    ) -> None: ...
    def executeStep(self, T_stop: int = ..., early_stop: bool = ...) -> None: ...
    def getBeta(self, step: int = ...) -> np.ndarray: ...
    def getIntercept(self, step: int = ...) -> float: ...
    def getBetaPath(self) -> np.ndarray: ...
    def solverTypeToString(self) -> str: ...
    def getCp(self) -> list[float]: ...
    def getCpWithSigma(self, sigma_hat_sq: float) -> list[float]: ...
    def getRSS(self) -> list[float]: ...
    def getR2(self) -> list[float]: ...
    def getDoF(self) -> list[int]: ...
    def getResiduals(self) -> np.ndarray: ...
    def getActions(self) -> list[list[int]]: ...
    def getActives(self) -> list[int]: ...
    def getInactives(self) -> list[int]: ...
    def getDroppedIndices(self) -> list[int]: ...
    def getNumActives(self) -> int: ...
    def getDummyStartIndex(self) -> int: ...
    def getNumSteps(self) -> int: ...
    def isConnected(self) -> bool: ...
    def reconnect(self, X: np.ndarray, D: np.ndarray) -> None: ...
    def restore(self, X: np.ndarray, D: np.ndarray, y: np.ndarray) -> None: ...
    def save(self, filepath: str) -> None: ...
    def load(self, filepath: str) -> None: ...

# ---------------------------------------------------------------------------
# TMP_Solver
# ---------------------------------------------------------------------------

class TMP_Solver:
    def __init__(
        self,
        X: np.ndarray,
        D: np.ndarray,
        y: np.ndarray,
        normalize: bool = ...,
        intercept: bool = ...,
        verbose: bool = ...,
    ) -> None: ...
    def executeStep(self, T_stop: int = ..., early_stop: bool = ...) -> None: ...
    def getBeta(self, step: int = ...) -> np.ndarray: ...
    def getIntercept(self, step: int = ...) -> float: ...
    def getBetaPath(self) -> np.ndarray: ...
    def solverTypeToString(self) -> str: ...
    def getCp(self) -> list[float]: ...
    def getCpWithSigma(self, sigma_hat_sq: float) -> list[float]: ...
    def getRSS(self) -> list[float]: ...
    def getR2(self) -> list[float]: ...
    def getDoF(self) -> list[int]: ...
    def getResiduals(self) -> np.ndarray: ...
    def getActions(self) -> list[list[int]]: ...
    def getActives(self) -> list[int]: ...
    def getInactives(self) -> list[int]: ...
    def getDroppedIndices(self) -> list[int]: ...
    def getNumActives(self) -> int: ...
    def getDummyStartIndex(self) -> int: ...
    def getNumSteps(self) -> int: ...
    def isConnected(self) -> bool: ...
    def reconnect(self, X: np.ndarray, D: np.ndarray) -> None: ...
    def restore(self, X: np.ndarray, D: np.ndarray, y: np.ndarray) -> None: ...
    def save(self, filepath: str) -> None: ...
    def load(self, filepath: str) -> None: ...

# ---------------------------------------------------------------------------
# TOOLS_Solver
# ---------------------------------------------------------------------------

class TOOLS_Solver:
    def __init__(
        self,
        X: np.ndarray,
        D: np.ndarray,
        y: np.ndarray,
        normalize: bool = ...,
        intercept: bool = ...,
        verbose: bool = ...,
    ) -> None: ...
    def executeStep(self, T_stop: int = ..., early_stop: bool = ...) -> None: ...
    def getBeta(self, step: int = ...) -> np.ndarray: ...
    def getIntercept(self, step: int = ...) -> float: ...
    def getBetaPath(self) -> np.ndarray: ...
    def solverTypeToString(self) -> str: ...
    def getCp(self) -> list[float]: ...
    def getCpWithSigma(self, sigma_hat_sq: float) -> list[float]: ...
    def getRSS(self) -> list[float]: ...
    def getR2(self) -> list[float]: ...
    def getDoF(self) -> list[int]: ...
    def getResiduals(self) -> np.ndarray: ...
    def getActions(self) -> list[list[int]]: ...
    def getActives(self) -> list[int]: ...
    def getInactives(self) -> list[int]: ...
    def getDroppedIndices(self) -> list[int]: ...
    def getNumActives(self) -> int: ...
    def getDummyStartIndex(self) -> int: ...
    def getNumSteps(self) -> int: ...
    def isConnected(self) -> bool: ...
    def reconnect(self, X: np.ndarray, D: np.ndarray) -> None: ...
    def restore(self, X: np.ndarray, D: np.ndarray, y: np.ndarray) -> None: ...
    def save(self, filepath: str) -> None: ...
    def load(self, filepath: str) -> None: ...

# ---------------------------------------------------------------------------
# TNCGMP_Solver
# ---------------------------------------------------------------------------

class TNCGMP_Solver:
    def __init__(
        self,
        X: np.ndarray,
        D: np.ndarray,
        y: np.ndarray,
        variant: NCGMPVariant = ...,
        normalize: bool = ...,
        intercept: bool = ...,
        verbose: bool = ...,
    ) -> None: ...
    def executeStep(self, T_stop: int = ..., early_stop: bool = ...) -> None: ...
    def getBeta(self, step: int = ...) -> np.ndarray: ...
    def getIntercept(self, step: int = ...) -> float: ...
    def getBetaPath(self) -> np.ndarray: ...
    def solverTypeToString(self) -> str: ...
    def getCp(self) -> list[float]: ...
    def getCpWithSigma(self, sigma_hat_sq: float) -> list[float]: ...
    def getRSS(self) -> list[float]: ...
    def getR2(self) -> list[float]: ...
    def getDoF(self) -> list[int]: ...
    def getResiduals(self) -> np.ndarray: ...
    def getActions(self) -> list[list[int]]: ...
    def getActives(self) -> list[int]: ...
    def getInactives(self) -> list[int]: ...
    def getDroppedIndices(self) -> list[int]: ...
    def getNumActives(self) -> int: ...
    def getDummyStartIndex(self) -> int: ...
    def getNumSteps(self) -> int: ...
    def isConnected(self) -> bool: ...
    def reconnect(self, X: np.ndarray, D: np.ndarray) -> None: ...
    def restore(self, X: np.ndarray, D: np.ndarray, y: np.ndarray) -> None: ...
    def save(self, filepath: str) -> None: ...
    def load(self, filepath: str) -> None: ...
