[mypy]
# suppress missing-stub warnings for untyped third-party libs
ignore_missing_imports = True

# or more surgically, per package:
[mypy-plotly.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True
