import numpy as np

# ---------------------------------------------------------------------------
# NormType
# ---------------------------------------------------------------------------

class NormType:
    L1: NormType
    L2: NormType

# ---------------------------------------------------------------------------
# ZScoreScaler
# ---------------------------------------------------------------------------

class ZScoreScaler:
    def __init__(self, with_mean: bool = ..., with_std: bool = ...) -> None: ...
    def fit(self, X: np.ndarray, threshold: float = ...) -> ZScoreScaler: ...
    def transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def inverse_transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def is_fitted(self) -> bool: ...
    def get_dropped_indices(self) -> list[int]: ...
    def get_means(self) -> np.ndarray: ...
    def get_scales(self) -> np.ndarray: ...
    def get_with_mean(self) -> bool: ...
    def get_with_std(self) -> bool: ...
    def save(self, filename: str) -> None: ...
    def load(self, filename: str) -> None: ...

# ---------------------------------------------------------------------------
# LpNormScaler
# ---------------------------------------------------------------------------

class LpNormScaler:
    def __init__(self, norm_type: NormType = ..., with_mean: bool = ...) -> None: ...
    def fit(self, X: np.ndarray, threshold: float = ...) -> LpNormScaler: ...
    def transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def inverse_transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def is_fitted(self) -> bool: ...
    def get_dropped_indices(self) -> list[int]: ...
    def get_means(self) -> np.ndarray: ...
    def get_scales(self) -> np.ndarray: ...
    def get_with_mean(self) -> bool: ...
    def get_with_norm(self) -> bool: ...
    def get_norm_type(self) -> NormType: ...
    def save(self, filename: str) -> None: ...
    def load(self, filename: str) -> None: ...

# ---------------------------------------------------------------------------
# RidgePath
# ---------------------------------------------------------------------------

class RidgePath:
    lambdas: list[float]
    coefficients: np.ndarray
    gcv_scores: list[float]
    df_effective: list[float]
    best_index: int
    def __init__(self) -> None: ...

# ---------------------------------------------------------------------------
# RidgeGCV
# ---------------------------------------------------------------------------

class RidgeGCV:
    def __init__(self) -> None: ...
    def fit(self, X: np.ndarray, y: np.ndarray) -> RidgeGCV: ...
    def solve(self, lambda_val: float) -> np.ndarray: ...
    def gcv(self, lambda_val: float) -> float: ...
    def predict(self, X_new: np.ndarray, lambda_val: float) -> np.ndarray: ...
    def predict_path(self, X_new: np.ndarray, lambdas: np.ndarray) -> np.ndarray: ...
    def solve_path(self, lambdas: np.ndarray) -> RidgePath: ...
    def gcv_optimal(self, num_grid: int = ..., tol: float = ...) -> float: ...
    def default_lambda_grid(self, num_lambda: int = ..., ratio: float = ...) -> np.ndarray: ...
    def n_samples(self) -> int: ...
    def n_features(self) -> int: ...
    def rank(self) -> int: ...

# ---------------------------------------------------------------------------
# RidgeCV
# ---------------------------------------------------------------------------

class RidgeCV:
    def __init__(self) -> None: ...
    def fit(
        self,
        X: np.ndarray,
        y: np.ndarray,
        num_folds: int = ...,
        n_lambda: int = ...,
        lambda_ratio: float = ...,
        seed: int = ...,
    ) -> RidgeCV: ...
    def cv_min(self) -> float: ...
    def cv_1se(self) -> float: ...
    def index_min(self) -> int: ...
    def index_1se(self) -> int: ...
    def get_lambdas(self) -> np.ndarray: ...
    def get_cv_errors(self) -> np.ndarray: ...
    def get_cv_std(self) -> np.ndarray: ...

# ---------------------------------------------------------------------------
# SVDResult
# ---------------------------------------------------------------------------

class SVDResult:
    U: np.ndarray
    """Left singular vectors (n × M)."""
    S: np.ndarray
    """Singular values (M)."""
    V: np.ndarray
    """Right singular vectors (p × M)."""
    def __init__(self) -> None: ...

# ---------------------------------------------------------------------------
# SVDSolver
# ---------------------------------------------------------------------------

class SVDSolver:
    """Computes the top-M truncated SVD of a matrix.

    Dispatches among direct (tall), Gram (wide), and randomized paths
    based on matrix shape.
    """
    def __init__(self) -> None: ...
    def compute(self, X: np.ndarray, M: int) -> SVDResult: ...

# ---------------------------------------------------------------------------
# PCAResult
# ---------------------------------------------------------------------------

class PCAResult:
    Z: np.ndarray
    """Score matrix (n × M)."""
    V: np.ndarray
    """Loading matrix (p × M)."""
    explained_variance: np.ndarray
    """Explained variance per component (M)."""
    def __init__(self) -> None: ...

# ---------------------------------------------------------------------------
# PCA
# ---------------------------------------------------------------------------

class PCA:
    """Fits PCA with optional in-place centering (RAII).

    When ``center=True``, the design matrix is modified in-place during
    ``fit()`` and restored when ``restore()`` is called.

    Note
    ----
    ``fit()`` requires a Fortran-contiguous (column-major) array.
    Pass ``np.asfortranarray(X)`` when in doubt.
    """
    def __init__(self, center: bool = ...) -> None: ...
    def fit(self, X: np.ndarray, M: int) -> PCAResult: ...
    def transform(self, X_new: np.ndarray) -> np.ndarray: ...
    def restore(self) -> None: ...
    def get_mean(self) -> np.ndarray: ...
    def get_loadings(self) -> np.ndarray: ...
    def get_explained_variance(self) -> np.ndarray: ...

# ---------------------------------------------------------------------------
# RidgeSolver
# ---------------------------------------------------------------------------

class RidgeSolver:
    """Solves ridge regression for a single lambda value.

    Dispatches between primal (n >= p) and dual (n < p) Cholesky solvers.
    """
    def __init__(self) -> None: ...
    @staticmethod
    def solve(X: np.ndarray, y: np.ndarray, lambda_val: float) -> np.ndarray: ...
