import numpy as np

# ---------------------------------------------------------------------------
# NormType
# ---------------------------------------------------------------------------

class NormType:
    L1: NormType
    L2: NormType

# ---------------------------------------------------------------------------
# ZScoreScaler
# ---------------------------------------------------------------------------

class ZScoreScaler:
    def __init__(self, with_mean: bool = ..., with_std: bool = ...) -> None: ...
    def fit(self, X: np.ndarray, threshold: float = ...) -> ZScoreScaler: ...
    def transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def inverse_transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def is_fitted(self) -> bool: ...
    def get_dropped_indices(self) -> list[int]: ...
    def get_means(self) -> np.ndarray: ...
    def get_scales(self) -> np.ndarray: ...
    def get_with_mean(self) -> bool: ...
    def get_with_std(self) -> bool: ...
    def save(self, filename: str) -> None: ...
    def load(self, filename: str) -> None: ...

# ---------------------------------------------------------------------------
# LpNormScaler
# ---------------------------------------------------------------------------

class LpNormScaler:
    def __init__(self, norm_type: NormType = ..., with_mean: bool = ...) -> None: ...
    def fit(self, X: np.ndarray, threshold: float = ...) -> LpNormScaler: ...
    def transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def inverse_transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def is_fitted(self) -> bool: ...
    def get_dropped_indices(self) -> list[int]: ...
    def get_means(self) -> np.ndarray: ...
    def get_scales(self) -> np.ndarray: ...
    def get_with_mean(self) -> bool: ...
    def get_with_norm(self) -> bool: ...
    def get_norm_type(self) -> NormType: ...
    def save(self, filename: str) -> None: ...
    def load(self, filename: str) -> None: ...

# ---------------------------------------------------------------------------
# RidgePath
# ---------------------------------------------------------------------------

class RidgePath:
    lambdas: list[float]
    coefficients: np.ndarray
    gcv_scores: list[float]
    df_effective: list[float]
    best_index: int
    def __init__(self) -> None: ...

# ---------------------------------------------------------------------------
# RidgeGCV
# ---------------------------------------------------------------------------

class RidgeGCV:
    def __init__(self) -> None: ...
    def fit(self, X: np.ndarray, y: np.ndarray) -> RidgeGCV: ...
    def solve(self, lambda_val: float) -> np.ndarray: ...
    def gcv(self, lambda_val: float) -> float: ...
    def predict(self, X_new: np.ndarray, lambda_val: float) -> np.ndarray: ...
    def predict_path(self, X_new: np.ndarray, lambdas: np.ndarray) -> np.ndarray: ...
    def solve_path(self, lambdas: np.ndarray) -> RidgePath: ...
    def gcv_optimal(self, num_grid: int = ..., tol: float = ...) -> float: ...
    def default_lambda_grid(self, num_lambda: int = ..., ratio: float = ...) -> np.ndarray: ...
    def n_samples(self) -> int: ...
    def n_features(self) -> int: ...
    def rank(self) -> int: ...

# ---------------------------------------------------------------------------
# RidgeCV
# ---------------------------------------------------------------------------

class RidgeCV:
    def __init__(self) -> None: ...
    def fit(
        self,
        X: np.ndarray,
        y: np.ndarray,
        num_folds: int = ...,
        n_lambda: int = ...,
        lambda_ratio: float = ...,
        seed: int = ...,
    ) -> RidgeCV: ...
    def cv_min(self) -> float: ...
    def cv_1se(self) -> float: ...
    def index_min(self) -> int: ...
    def index_1se(self) -> int: ...
    def get_lambdas(self) -> np.ndarray: ...
    def get_cv_errors(self) -> np.ndarray: ...
    def get_cv_std(self) -> np.ndarray: ...
