import numpy as np

# ---------------------------------------------------------------------------
# NormType
# ---------------------------------------------------------------------------

class NormType:
    L1: NormType
    L2: NormType

# ---------------------------------------------------------------------------
# ZScoreScaler
# ---------------------------------------------------------------------------

class ZScoreScaler:
    def __init__(self, with_mean: bool = ..., with_std: bool = ...) -> None: ...
    def fit(self, X: np.ndarray, threshold: float = ...) -> ZScoreScaler: ...
    def transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def inverse_transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def is_fitted(self) -> bool: ...
    def get_dropped_indices(self) -> list[int]: ...
    def get_means(self) -> np.ndarray: ...
    def get_scales(self) -> np.ndarray: ...
    def get_with_mean(self) -> bool: ...
    def get_with_std(self) -> bool: ...
    def save(self, filename: str) -> None: ...
    def load(self, filename: str) -> None: ...

# ---------------------------------------------------------------------------
# LpNormScaler
# ---------------------------------------------------------------------------

class LpNormScaler:
    def __init__(self, norm_type: NormType = ..., with_mean: bool = ...) -> None: ...
    def fit(self, X: np.ndarray, threshold: float = ...) -> LpNormScaler: ...
    def transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def inverse_transform_inplace(self, X: np.ndarray) -> np.ndarray: ...
    def is_fitted(self) -> bool: ...
    def get_dropped_indices(self) -> list[int]: ...
    def get_means(self) -> np.ndarray: ...
    def get_scales(self) -> np.ndarray: ...
    def get_with_mean(self) -> bool: ...
    def get_with_norm(self) -> bool: ...
    def get_norm_type(self) -> NormType: ...
    def save(self, filename: str) -> None: ...
    def load(self, filename: str) -> None: ...

# ---------------------------------------------------------------------------
# SVDResult
# ---------------------------------------------------------------------------

class SVDResult:
    U: np.ndarray
    """Left singular vectors (n × M)."""
    S: np.ndarray
    """Singular values (M)."""
    V: np.ndarray
    """Right singular vectors (p × M)."""
    def __init__(self) -> None: ...

# ---------------------------------------------------------------------------
# SVDSolver
# ---------------------------------------------------------------------------

class SVDSolver:
    """Computes the top-M truncated SVD of a matrix.

    Dispatches among direct (tall), Gram (wide), and randomized paths
    based on matrix shape.
    """
    def __init__(self) -> None: ...
    def compute(self, X: np.ndarray, M: int) -> SVDResult: ...

# ---------------------------------------------------------------------------
# PCAResult
# ---------------------------------------------------------------------------

class PCAResult:
    Z: np.ndarray
    """Score matrix (n × M)."""
    V: np.ndarray
    """Loading matrix (p × M)."""
    explained_variance: np.ndarray
    """Explained variance per component (M)."""
    def __init__(self) -> None: ...

# ---------------------------------------------------------------------------
# PCA
# ---------------------------------------------------------------------------

class PCA:
    """Fits PCA with optional in-place centering (RAII).

    When ``center=True``, the design matrix is modified in-place during
    ``fit()`` and restored when ``restore()`` is called.

    Note
    ----
    ``fit()`` requires a Fortran-contiguous (column-major) array.
    Pass ``np.asfortranarray(X)`` when in doubt.
    """
    def __init__(self, center: bool = ..., normalize: bool = ...) -> None: ...
    def fit(self, X: np.ndarray, M: int) -> PCAResult: ...
    def transform(self, X_new: np.ndarray) -> np.ndarray: ...
    def restore(self) -> None: ...
    def get_mean(self) -> np.ndarray: ...
    def get_means(self) -> np.ndarray: ...
    def get_norms(self) -> np.ndarray: ...
    def get_loadings(self) -> np.ndarray: ...
    def get_explained_variance(self) -> np.ndarray: ...

# ---------------------------------------------------------------------------
# RidgeSolver
# ---------------------------------------------------------------------------

class RidgeSolver:
    """Solves ridge regression for a single lambda value.

    Dispatches between primal (n >= p) and dual (n < p) Cholesky solvers.
    """
    def __init__(self) -> None: ...
    @staticmethod
    def solve(X: np.ndarray, y: np.ndarray, lambda_val: float) -> np.ndarray: ...
