// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "TRexSelector_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_agglomerative_cluster
NumericMatrix rcpp_agglomerative_cluster(const Eigen::Map<Eigen::MatrixXd>& data, int method_idx, int metric_idx, bool use_mmap);
RcppExport SEXP _TRexSelector_rcpp_agglomerative_cluster(SEXP dataSEXP, SEXP method_idxSEXP, SEXP metric_idxSEXP, SEXP use_mmapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type method_idx(method_idxSEXP);
    Rcpp::traits::input_parameter< int >::type metric_idx(metric_idxSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mmap(use_mmapSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_agglomerative_cluster(data, method_idx, metric_idx, use_mmap));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cut_tree
IntegerVector rcpp_cut_tree(const Eigen::Map<Eigen::MatrixXd>& linkage, int num_orig_objs, int num_clusters);
RcppExport SEXP _TRexSelector_rcpp_cut_tree(SEXP linkageSEXP, SEXP num_orig_objsSEXP, SEXP num_clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type linkage(linkageSEXP);
    Rcpp::traits::input_parameter< int >::type num_orig_objs(num_orig_objsSEXP);
    Rcpp::traits::input_parameter< int >::type num_clusters(num_clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cut_tree(linkage, num_orig_objs, num_clusters));
    return rcpp_result_gen;
END_RCPP
}
// zscore_scaler_create
XPtr<ZScoreScaler> zscore_scaler_create(bool with_mean, bool with_std);
RcppExport SEXP _TRexSelector_zscore_scaler_create(SEXP with_meanSEXP, SEXP with_stdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type with_mean(with_meanSEXP);
    Rcpp::traits::input_parameter< bool >::type with_std(with_stdSEXP);
    rcpp_result_gen = Rcpp::wrap(zscore_scaler_create(with_mean, with_std));
    return rcpp_result_gen;
END_RCPP
}
// zscore_scaler_fit
void zscore_scaler_fit(XPtr<ZScoreScaler> ptr, Eigen::Map<Eigen::MatrixXd> X, double threshold);
RcppExport SEXP _TRexSelector_zscore_scaler_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ZScoreScaler> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    zscore_scaler_fit(ptr, X, threshold);
    return R_NilValue;
END_RCPP
}
// zscore_scaler_transform_inplace
void zscore_scaler_transform_inplace(XPtr<ZScoreScaler> ptr, Eigen::Map<Eigen::MatrixXd> X);
RcppExport SEXP _TRexSelector_zscore_scaler_transform_inplace(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ZScoreScaler> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    zscore_scaler_transform_inplace(ptr, X);
    return R_NilValue;
END_RCPP
}
// zscore_scaler_inverse_transform_inplace
void zscore_scaler_inverse_transform_inplace(XPtr<ZScoreScaler> ptr, Eigen::Map<Eigen::MatrixXd> X);
RcppExport SEXP _TRexSelector_zscore_scaler_inverse_transform_inplace(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ZScoreScaler> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    zscore_scaler_inverse_transform_inplace(ptr, X);
    return R_NilValue;
END_RCPP
}
// zscore_scaler_is_fitted
bool zscore_scaler_is_fitted(XPtr<ZScoreScaler> ptr);
RcppExport SEXP _TRexSelector_zscore_scaler_is_fitted(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ZScoreScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(zscore_scaler_is_fitted(ptr));
    return rcpp_result_gen;
END_RCPP
}
// zscore_scaler_get_dropped_indices
std::vector<std::size_t> zscore_scaler_get_dropped_indices(XPtr<ZScoreScaler> ptr);
RcppExport SEXP _TRexSelector_zscore_scaler_get_dropped_indices(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ZScoreScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(zscore_scaler_get_dropped_indices(ptr));
    return rcpp_result_gen;
END_RCPP
}
// zscore_scaler_get_with_mean
bool zscore_scaler_get_with_mean(XPtr<ZScoreScaler> ptr);
RcppExport SEXP _TRexSelector_zscore_scaler_get_with_mean(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ZScoreScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(zscore_scaler_get_with_mean(ptr));
    return rcpp_result_gen;
END_RCPP
}
// zscore_scaler_get_with_std
bool zscore_scaler_get_with_std(XPtr<ZScoreScaler> ptr);
RcppExport SEXP _TRexSelector_zscore_scaler_get_with_std(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ZScoreScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(zscore_scaler_get_with_std(ptr));
    return rcpp_result_gen;
END_RCPP
}
// zscore_scaler_get_means
Eigen::VectorXd zscore_scaler_get_means(XPtr<ZScoreScaler> ptr);
RcppExport SEXP _TRexSelector_zscore_scaler_get_means(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ZScoreScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(zscore_scaler_get_means(ptr));
    return rcpp_result_gen;
END_RCPP
}
// zscore_scaler_get_scales
Eigen::VectorXd zscore_scaler_get_scales(XPtr<ZScoreScaler> ptr);
RcppExport SEXP _TRexSelector_zscore_scaler_get_scales(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ZScoreScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(zscore_scaler_get_scales(ptr));
    return rcpp_result_gen;
END_RCPP
}
// zscore_scaler_save
void zscore_scaler_save(XPtr<ZScoreScaler> ptr, const std::string& filename);
RcppExport SEXP _TRexSelector_zscore_scaler_save(SEXP ptrSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ZScoreScaler> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    zscore_scaler_save(ptr, filename);
    return R_NilValue;
END_RCPP
}
// zscore_scaler_load
void zscore_scaler_load(XPtr<ZScoreScaler> ptr, const std::string& filename);
RcppExport SEXP _TRexSelector_zscore_scaler_load(SEXP ptrSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ZScoreScaler> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    zscore_scaler_load(ptr, filename);
    return R_NilValue;
END_RCPP
}
// lpnorm_scaler_create
XPtr<LpNormScaler> lpnorm_scaler_create(int norm_type, bool with_mean);
RcppExport SEXP _TRexSelector_lpnorm_scaler_create(SEXP norm_typeSEXP, SEXP with_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type norm_type(norm_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type with_mean(with_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(lpnorm_scaler_create(norm_type, with_mean));
    return rcpp_result_gen;
END_RCPP
}
// lpnorm_scaler_fit
void lpnorm_scaler_fit(XPtr<LpNormScaler> ptr, Eigen::Map<Eigen::MatrixXd> X, double threshold);
RcppExport SEXP _TRexSelector_lpnorm_scaler_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    lpnorm_scaler_fit(ptr, X, threshold);
    return R_NilValue;
END_RCPP
}
// lpnorm_scaler_transform_inplace
void lpnorm_scaler_transform_inplace(XPtr<LpNormScaler> ptr, Eigen::Map<Eigen::MatrixXd> X);
RcppExport SEXP _TRexSelector_lpnorm_scaler_transform_inplace(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    lpnorm_scaler_transform_inplace(ptr, X);
    return R_NilValue;
END_RCPP
}
// lpnorm_scaler_inverse_transform_inplace
void lpnorm_scaler_inverse_transform_inplace(XPtr<LpNormScaler> ptr, Eigen::Map<Eigen::MatrixXd> X);
RcppExport SEXP _TRexSelector_lpnorm_scaler_inverse_transform_inplace(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    lpnorm_scaler_inverse_transform_inplace(ptr, X);
    return R_NilValue;
END_RCPP
}
// lpnorm_scaler_is_fitted
bool lpnorm_scaler_is_fitted(XPtr<LpNormScaler> ptr);
RcppExport SEXP _TRexSelector_lpnorm_scaler_is_fitted(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(lpnorm_scaler_is_fitted(ptr));
    return rcpp_result_gen;
END_RCPP
}
// lpnorm_scaler_get_dropped_indices
std::vector<std::size_t> lpnorm_scaler_get_dropped_indices(XPtr<LpNormScaler> ptr);
RcppExport SEXP _TRexSelector_lpnorm_scaler_get_dropped_indices(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(lpnorm_scaler_get_dropped_indices(ptr));
    return rcpp_result_gen;
END_RCPP
}
// lpnorm_scaler_get_means
Eigen::VectorXd lpnorm_scaler_get_means(XPtr<LpNormScaler> ptr);
RcppExport SEXP _TRexSelector_lpnorm_scaler_get_means(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(lpnorm_scaler_get_means(ptr));
    return rcpp_result_gen;
END_RCPP
}
// lpnorm_scaler_get_scales
Eigen::VectorXd lpnorm_scaler_get_scales(XPtr<LpNormScaler> ptr);
RcppExport SEXP _TRexSelector_lpnorm_scaler_get_scales(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(lpnorm_scaler_get_scales(ptr));
    return rcpp_result_gen;
END_RCPP
}
// lpnorm_scaler_get_with_mean
bool lpnorm_scaler_get_with_mean(XPtr<LpNormScaler> ptr);
RcppExport SEXP _TRexSelector_lpnorm_scaler_get_with_mean(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(lpnorm_scaler_get_with_mean(ptr));
    return rcpp_result_gen;
END_RCPP
}
// lpnorm_scaler_get_with_norm
bool lpnorm_scaler_get_with_norm(XPtr<LpNormScaler> ptr);
RcppExport SEXP _TRexSelector_lpnorm_scaler_get_with_norm(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(lpnorm_scaler_get_with_norm(ptr));
    return rcpp_result_gen;
END_RCPP
}
// lpnorm_scaler_get_norm_type
int lpnorm_scaler_get_norm_type(XPtr<LpNormScaler> ptr);
RcppExport SEXP _TRexSelector_lpnorm_scaler_get_norm_type(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(lpnorm_scaler_get_norm_type(ptr));
    return rcpp_result_gen;
END_RCPP
}
// lpnorm_scaler_save
void lpnorm_scaler_save(XPtr<LpNormScaler> ptr, const std::string& filename);
RcppExport SEXP _TRexSelector_lpnorm_scaler_save(SEXP ptrSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    lpnorm_scaler_save(ptr, filename);
    return R_NilValue;
END_RCPP
}
// lpnorm_scaler_load
void lpnorm_scaler_load(XPtr<LpNormScaler> ptr, const std::string& filename);
RcppExport SEXP _TRexSelector_lpnorm_scaler_load(SEXP ptrSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<LpNormScaler> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    lpnorm_scaler_load(ptr, filename);
    return R_NilValue;
END_RCPP
}
// ridge_gcv_create
XPtr<ridge_gcv> ridge_gcv_create();
RcppExport SEXP _TRexSelector_ridge_gcv_create() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ridge_gcv_create());
    return rcpp_result_gen;
END_RCPP
}
// ridge_gcv_fit
void ridge_gcv_fit(XPtr<ridge_gcv> ptr, const Eigen::MatrixXd& X, const Eigen::VectorXd& y);
RcppExport SEXP _TRexSelector_ridge_gcv_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_gcv> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    ridge_gcv_fit(ptr, X, y);
    return R_NilValue;
END_RCPP
}
// ridge_gcv_solve
Eigen::VectorXd ridge_gcv_solve(XPtr<ridge_gcv> ptr, double lambda_val);
RcppExport SEXP _TRexSelector_ridge_gcv_solve(SEXP ptrSEXP, SEXP lambda_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_gcv> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_val(lambda_valSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_gcv_solve(ptr, lambda_val));
    return rcpp_result_gen;
END_RCPP
}
// ridge_gcv_gcv_score
double ridge_gcv_gcv_score(XPtr<ridge_gcv> ptr, double lambda_val);
RcppExport SEXP _TRexSelector_ridge_gcv_gcv_score(SEXP ptrSEXP, SEXP lambda_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_gcv> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_val(lambda_valSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_gcv_gcv_score(ptr, lambda_val));
    return rcpp_result_gen;
END_RCPP
}
// ridge_gcv_predict
Eigen::VectorXd ridge_gcv_predict(XPtr<ridge_gcv> ptr, const Eigen::MatrixXd& X_new, double lambda_val);
RcppExport SEXP _TRexSelector_ridge_gcv_predict(SEXP ptrSEXP, SEXP X_newSEXP, SEXP lambda_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_gcv> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_new(X_newSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_val(lambda_valSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_gcv_predict(ptr, X_new, lambda_val));
    return rcpp_result_gen;
END_RCPP
}
// ridge_gcv_predict_path
Eigen::MatrixXd ridge_gcv_predict_path(XPtr<ridge_gcv> ptr, const Eigen::MatrixXd& X_new, const Eigen::VectorXd& lambdas);
RcppExport SEXP _TRexSelector_ridge_gcv_predict_path(SEXP ptrSEXP, SEXP X_newSEXP, SEXP lambdasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_gcv> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_new(X_newSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lambdas(lambdasSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_gcv_predict_path(ptr, X_new, lambdas));
    return rcpp_result_gen;
END_RCPP
}
// ridge_gcv_default_lambda_grid
Eigen::VectorXd ridge_gcv_default_lambda_grid(XPtr<ridge_gcv> ptr, int num_lambda, double ratio);
RcppExport SEXP _TRexSelector_ridge_gcv_default_lambda_grid(SEXP ptrSEXP, SEXP num_lambdaSEXP, SEXP ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_gcv> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type num_lambda(num_lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type ratio(ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_gcv_default_lambda_grid(ptr, num_lambda, ratio));
    return rcpp_result_gen;
END_RCPP
}
// ridge_gcv_n_samples
int ridge_gcv_n_samples(XPtr<ridge_gcv> ptr);
RcppExport SEXP _TRexSelector_ridge_gcv_n_samples(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_gcv> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_gcv_n_samples(ptr));
    return rcpp_result_gen;
END_RCPP
}
// ridge_gcv_n_features
int ridge_gcv_n_features(XPtr<ridge_gcv> ptr);
RcppExport SEXP _TRexSelector_ridge_gcv_n_features(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_gcv> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_gcv_n_features(ptr));
    return rcpp_result_gen;
END_RCPP
}
// ridge_gcv_rank
int ridge_gcv_rank(XPtr<ridge_gcv> ptr);
RcppExport SEXP _TRexSelector_ridge_gcv_rank(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_gcv> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_gcv_rank(ptr));
    return rcpp_result_gen;
END_RCPP
}
// ridge_gcv_solve_path
List ridge_gcv_solve_path(XPtr<ridge_gcv> ptr, const Eigen::VectorXd& lambdas);
RcppExport SEXP _TRexSelector_ridge_gcv_solve_path(SEXP ptrSEXP, SEXP lambdasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_gcv> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type lambdas(lambdasSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_gcv_solve_path(ptr, lambdas));
    return rcpp_result_gen;
END_RCPP
}
// ridge_gcv_optimal
double ridge_gcv_optimal(XPtr<ridge_gcv> ptr, int num_grid, double tol);
RcppExport SEXP _TRexSelector_ridge_gcv_optimal(SEXP ptrSEXP, SEXP num_gridSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_gcv> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type num_grid(num_gridSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_gcv_optimal(ptr, num_grid, tol));
    return rcpp_result_gen;
END_RCPP
}
// ridge_cv_create
XPtr<ridge_cv> ridge_cv_create();
RcppExport SEXP _TRexSelector_ridge_cv_create() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ridge_cv_create());
    return rcpp_result_gen;
END_RCPP
}
// ridge_cv_fit
void ridge_cv_fit(XPtr<ridge_cv> ptr, const Eigen::MatrixXd& X, const Eigen::VectorXd& y, int num_folds, int n_lambda, double lambda_ratio, unsigned int seed);
RcppExport SEXP _TRexSelector_ridge_cv_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP, SEXP num_foldsSEXP, SEXP n_lambdaSEXP, SEXP lambda_ratioSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_cv> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type num_folds(num_foldsSEXP);
    Rcpp::traits::input_parameter< int >::type n_lambda(n_lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_ratio(lambda_ratioSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    ridge_cv_fit(ptr, X, y, num_folds, n_lambda, lambda_ratio, seed);
    return R_NilValue;
END_RCPP
}
// ridge_cv_min
double ridge_cv_min(XPtr<ridge_cv> ptr);
RcppExport SEXP _TRexSelector_ridge_cv_min(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_cv> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_cv_min(ptr));
    return rcpp_result_gen;
END_RCPP
}
// ridge_cv_1se
double ridge_cv_1se(XPtr<ridge_cv> ptr);
RcppExport SEXP _TRexSelector_ridge_cv_1se(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_cv> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_cv_1se(ptr));
    return rcpp_result_gen;
END_RCPP
}
// ridge_cv_index_min
int ridge_cv_index_min(XPtr<ridge_cv> ptr);
RcppExport SEXP _TRexSelector_ridge_cv_index_min(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_cv> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_cv_index_min(ptr));
    return rcpp_result_gen;
END_RCPP
}
// ridge_cv_index_1se
int ridge_cv_index_1se(XPtr<ridge_cv> ptr);
RcppExport SEXP _TRexSelector_ridge_cv_index_1se(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_cv> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_cv_index_1se(ptr));
    return rcpp_result_gen;
END_RCPP
}
// ridge_cv_get_lambdas
Eigen::VectorXd ridge_cv_get_lambdas(XPtr<ridge_cv> ptr);
RcppExport SEXP _TRexSelector_ridge_cv_get_lambdas(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_cv> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_cv_get_lambdas(ptr));
    return rcpp_result_gen;
END_RCPP
}
// ridge_cv_get_cv_errors
Eigen::VectorXd ridge_cv_get_cv_errors(XPtr<ridge_cv> ptr);
RcppExport SEXP _TRexSelector_ridge_cv_get_cv_errors(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_cv> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_cv_get_cv_errors(ptr));
    return rcpp_result_gen;
END_RCPP
}
// ridge_cv_get_cv_std
Eigen::VectorXd ridge_cv_get_cv_std(XPtr<ridge_cv> ptr);
RcppExport SEXP _TRexSelector_ridge_cv_get_cv_std(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ridge_cv> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_cv_get_cv_std(ptr));
    return rcpp_result_gen;
END_RCPP
}
// trex_selector_create
XPtr<RTRexSelector> trex_selector_create(Eigen::Map<Eigen::MatrixXd> X, Eigen::Map<Eigen::VectorXd> y, double tFDR, Rcpp::List control_list, int seed, bool verbose);
RcppExport SEXP _TRexSelector_trex_selector_create(SEXP XSEXP, SEXP ySEXP, SEXP tFDRSEXP, SEXP control_listSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tFDR(tFDRSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control_list(control_listSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(trex_selector_create(X, y, tFDR, control_list, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// trex_selector_mmap_create
XPtr<RTRexSelector> trex_selector_mmap_create(XPtr<trex::utils::memmap::MemoryMappedMatrix<double>> X_ptr, Eigen::Map<Eigen::VectorXd> y, double tFDR, Rcpp::List control_list, int seed, bool verbose);
RcppExport SEXP _TRexSelector_trex_selector_mmap_create(SEXP X_ptrSEXP, SEXP ySEXP, SEXP tFDRSEXP, SEXP control_listSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<trex::utils::memmap::MemoryMappedMatrix<double>> >::type X_ptr(X_ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tFDR(tFDRSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control_list(control_listSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(trex_selector_mmap_create(X_ptr, y, tFDR, control_list, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// trex_selector_select
List trex_selector_select(XPtr<RTRexSelector> r_ptr);
RcppExport SEXP _TRexSelector_trex_selector_select(SEXP r_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<RTRexSelector> >::type r_ptr(r_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(trex_selector_select(r_ptr));
    return rcpp_result_gen;
END_RCPP
}
// trex_selector_get_selected_indices
IntegerVector trex_selector_get_selected_indices(XPtr<RTRexSelector> r_ptr);
RcppExport SEXP _TRexSelector_trex_selector_get_selected_indices(SEXP r_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<RTRexSelector> >::type r_ptr(r_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(trex_selector_get_selected_indices(r_ptr));
    return rcpp_result_gen;
END_RCPP
}
// trex_da_create
XPtr<RTRexDASelector> trex_da_create(Eigen::Map<Eigen::MatrixXd> X, Eigen::Map<Eigen::VectorXd> y, double tFDR, Rcpp::List da_control_list, Rcpp::List trex_control_list, int seed, bool verbose);
RcppExport SEXP _TRexSelector_trex_da_create(SEXP XSEXP, SEXP ySEXP, SEXP tFDRSEXP, SEXP da_control_listSEXP, SEXP trex_control_listSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tFDR(tFDRSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type da_control_list(da_control_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type trex_control_list(trex_control_listSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(trex_da_create(X, y, tFDR, da_control_list, trex_control_list, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// trex_da_mmap_create
XPtr<RTRexDASelector> trex_da_mmap_create(XPtr<trex::utils::memmap::MemoryMappedMatrix<double>> X_ptr, Eigen::Map<Eigen::VectorXd> y, double tFDR, Rcpp::List da_control_list, Rcpp::List trex_control_list, int seed, bool verbose);
RcppExport SEXP _TRexSelector_trex_da_mmap_create(SEXP X_ptrSEXP, SEXP ySEXP, SEXP tFDRSEXP, SEXP da_control_listSEXP, SEXP trex_control_listSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<trex::utils::memmap::MemoryMappedMatrix<double>> >::type X_ptr(X_ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tFDR(tFDRSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type da_control_list(da_control_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type trex_control_list(trex_control_listSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(trex_da_mmap_create(X_ptr, y, tFDR, da_control_list, trex_control_list, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// trex_da_select
List trex_da_select(XPtr<RTRexDASelector> r_ptr);
RcppExport SEXP _TRexSelector_trex_da_select(SEXP r_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<RTRexDASelector> >::type r_ptr(r_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(trex_da_select(r_ptr));
    return rcpp_result_gen;
END_RCPP
}
// trex_da_get_selected_indices
IntegerVector trex_da_get_selected_indices(XPtr<RTRexDASelector> r_ptr);
RcppExport SEXP _TRexSelector_trex_da_get_selected_indices(SEXP r_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<RTRexDASelector> >::type r_ptr(r_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(trex_da_get_selected_indices(r_ptr));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_lars_create
XPtr<TSolver_Base> tsolver_lars_create(Eigen::Map<Eigen::MatrixXd> X, Eigen::Map<Eigen::MatrixXd> D, Eigen::Map<Eigen::VectorXd> y);
RcppExport SEXP _TRexSelector_tsolver_lars_create(SEXP XSEXP, SEXP DSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type D(DSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_lars_create(X, D, y));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_omp_create
XPtr<TSolver_Base> tsolver_omp_create(Eigen::Map<Eigen::MatrixXd> X, Eigen::Map<Eigen::MatrixXd> D, Eigen::Map<Eigen::VectorXd> y);
RcppExport SEXP _TRexSelector_tsolver_omp_create(SEXP XSEXP, SEXP DSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type D(DSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_omp_create(X, D, y));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_lars_mmap_create
XPtr<TSolver_Base> tsolver_lars_mmap_create(XPtr<MemoryMappedMatrix<double>> X_ptr, Eigen::Map<Eigen::MatrixXd> D, Eigen::Map<Eigen::VectorXd> y);
RcppExport SEXP _TRexSelector_tsolver_lars_mmap_create(SEXP X_ptrSEXP, SEXP DSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<MemoryMappedMatrix<double>> >::type X_ptr(X_ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type D(DSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_lars_mmap_create(X_ptr, D, y));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_omp_mmap_create
XPtr<TSolver_Base> tsolver_omp_mmap_create(XPtr<MemoryMappedMatrix<double>> X_ptr, Eigen::Map<Eigen::MatrixXd> D, Eigen::Map<Eigen::VectorXd> y);
RcppExport SEXP _TRexSelector_tsolver_omp_mmap_create(SEXP X_ptrSEXP, SEXP DSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<MemoryMappedMatrix<double>> >::type X_ptr(X_ptrSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type D(DSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_omp_mmap_create(X_ptr, D, y));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_execute_step
void tsolver_execute_step(XPtr<TSolver_Base> ptr, int T_stop, bool early_stop);
RcppExport SEXP _TRexSelector_tsolver_execute_step(SEXP ptrSEXP, SEXP T_stopSEXP, SEXP early_stopSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<TSolver_Base> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type T_stop(T_stopSEXP);
    Rcpp::traits::input_parameter< bool >::type early_stop(early_stopSEXP);
    tsolver_execute_step(ptr, T_stop, early_stop);
    return R_NilValue;
END_RCPP
}
// tsolver_get_beta
Eigen::VectorXd tsolver_get_beta(XPtr<TSolver_Base> ptr, int step);
RcppExport SEXP _TRexSelector_tsolver_get_beta(SEXP ptrSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<TSolver_Base> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_get_beta(ptr, step));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_get_cp
NumericVector tsolver_get_cp(XPtr<TSolver_Base> ptr);
RcppExport SEXP _TRexSelector_tsolver_get_cp(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<TSolver_Base> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_get_cp(ptr));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_get_rss
NumericVector tsolver_get_rss(XPtr<TSolver_Base> ptr);
RcppExport SEXP _TRexSelector_tsolver_get_rss(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<TSolver_Base> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_get_rss(ptr));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_get_r2
NumericVector tsolver_get_r2(XPtr<TSolver_Base> ptr);
RcppExport SEXP _TRexSelector_tsolver_get_r2(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<TSolver_Base> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_get_r2(ptr));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_get_dof
NumericVector tsolver_get_dof(XPtr<TSolver_Base> ptr);
RcppExport SEXP _TRexSelector_tsolver_get_dof(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<TSolver_Base> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_get_dof(ptr));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_get_actives
NumericVector tsolver_get_actives(XPtr<TSolver_Base> ptr);
RcppExport SEXP _TRexSelector_tsolver_get_actives(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<TSolver_Base> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_get_actives(ptr));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_get_inactives
NumericVector tsolver_get_inactives(XPtr<TSolver_Base> ptr);
RcppExport SEXP _TRexSelector_tsolver_get_inactives(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<TSolver_Base> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_get_inactives(ptr));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_get_intercept
double tsolver_get_intercept(XPtr<TSolver_Base> ptr, int step);
RcppExport SEXP _TRexSelector_tsolver_get_intercept(SEXP ptrSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<TSolver_Base> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(tsolver_get_intercept(ptr, step));
    return rcpp_result_gen;
END_RCPP
}
// tsolver_save
void tsolver_save(XPtr<TSolver_Base> ptr, const std::string& filename);
RcppExport SEXP _TRexSelector_tsolver_save(SEXP ptrSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<TSolver_Base> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    tsolver_save(ptr, filename);
    return R_NilValue;
END_RCPP
}
// tsolver_load
void tsolver_load(XPtr<TSolver_Base> ptr, const std::string& filename);
RcppExport SEXP _TRexSelector_tsolver_load(SEXP ptrSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<TSolver_Base> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    tsolver_load(ptr, filename);
    return R_NilValue;
END_RCPP
}
// mmap_matrix_create
XPtr<MemoryMappedMatrix<double>> mmap_matrix_create(const std::string& filename, int rows, int cols, int mode_idx);
RcppExport SEXP _TRexSelector_mmap_matrix_create(SEXP filenameSEXP, SEXP rowsSEXP, SEXP colsSEXP, SEXP mode_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< int >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< int >::type mode_idx(mode_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(mmap_matrix_create(filename, rows, cols, mode_idx));
    return rcpp_result_gen;
END_RCPP
}
// mmap_matrix_to_r_matrix
NumericMatrix mmap_matrix_to_r_matrix(XPtr<MemoryMappedMatrix<double>> ptr);
RcppExport SEXP _TRexSelector_mmap_matrix_to_r_matrix(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<MemoryMappedMatrix<double>> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(mmap_matrix_to_r_matrix(ptr));
    return rcpp_result_gen;
END_RCPP
}
// convert_to_memory_mapped_matrix
void convert_to_memory_mapped_matrix(NumericMatrix mat, const std::string& filename);
RcppExport SEXP _TRexSelector_convert_to_memory_mapped_matrix(SEXP matSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    convert_to_memory_mapped_matrix(mat, filename);
    return R_NilValue;
END_RCPP
}
// mmap_matrix_rows
int mmap_matrix_rows(XPtr<MemoryMappedMatrix<double>> ptr);
RcppExport SEXP _TRexSelector_mmap_matrix_rows(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<MemoryMappedMatrix<double>> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(mmap_matrix_rows(ptr));
    return rcpp_result_gen;
END_RCPP
}
// mmap_matrix_cols
int mmap_matrix_cols(XPtr<MemoryMappedMatrix<double>> ptr);
RcppExport SEXP _TRexSelector_mmap_matrix_cols(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<MemoryMappedMatrix<double>> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(mmap_matrix_cols(ptr));
    return rcpp_result_gen;
END_RCPP
}
// mmap_matrix_size
int mmap_matrix_size(XPtr<MemoryMappedMatrix<double>> ptr);
RcppExport SEXP _TRexSelector_mmap_matrix_size(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<MemoryMappedMatrix<double>> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(mmap_matrix_size(ptr));
    return rcpp_result_gen;
END_RCPP
}
// mmap_matrix_read_range
NumericMatrix mmap_matrix_read_range(XPtr<MemoryMappedMatrix<double>> ptr, int row_start, int row_count, int col_start, int col_count);
RcppExport SEXP _TRexSelector_mmap_matrix_read_range(SEXP ptrSEXP, SEXP row_startSEXP, SEXP row_countSEXP, SEXP col_startSEXP, SEXP col_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<MemoryMappedMatrix<double>> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type row_start(row_startSEXP);
    Rcpp::traits::input_parameter< int >::type row_count(row_countSEXP);
    Rcpp::traits::input_parameter< int >::type col_start(col_startSEXP);
    Rcpp::traits::input_parameter< int >::type col_count(col_countSEXP);
    rcpp_result_gen = Rcpp::wrap(mmap_matrix_read_range(ptr, row_start, row_count, col_start, col_count));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_compute_fdp
double rcpp_compute_fdp(const std::vector<std::size_t>& selected_indices, const std::vector<std::size_t>& true_support);
RcppExport SEXP _TRexSelector_rcpp_compute_fdp(SEXP selected_indicesSEXP, SEXP true_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::size_t>& >::type selected_indices(selected_indicesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::size_t>& >::type true_support(true_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_fdp(selected_indices, true_support));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_compute_tpp
double rcpp_compute_tpp(const std::vector<std::size_t>& selected_indices, const std::vector<std::size_t>& true_support);
RcppExport SEXP _TRexSelector_rcpp_compute_tpp(SEXP selected_indicesSEXP, SEXP true_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::size_t>& >::type selected_indices(selected_indicesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::size_t>& >::type true_support(true_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_tpp(selected_indices, true_support));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_compute_precision
double rcpp_compute_precision(const std::vector<std::size_t>& selected_indices, const std::vector<std::size_t>& true_support);
RcppExport SEXP _TRexSelector_rcpp_compute_precision(SEXP selected_indicesSEXP, SEXP true_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::size_t>& >::type selected_indices(selected_indicesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::size_t>& >::type true_support(true_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_precision(selected_indices, true_support));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_compute_recall
double rcpp_compute_recall(const std::vector<std::size_t>& selected_indices, const std::vector<std::size_t>& true_support);
RcppExport SEXP _TRexSelector_rcpp_compute_recall(SEXP selected_indicesSEXP, SEXP true_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::size_t>& >::type selected_indices(selected_indicesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::size_t>& >::type true_support(true_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_recall(selected_indices, true_support));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_compute_fdp_dense
double rcpp_compute_fdp_dense(const Eigen::VectorXd& beta_hat, const Eigen::VectorXd& beta, double eps);
RcppExport SEXP _TRexSelector_rcpp_compute_fdp_dense(SEXP beta_hatSEXP, SEXP betaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta_hat(beta_hatSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_fdp_dense(beta_hat, beta, eps));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_compute_tpp_dense
double rcpp_compute_tpp_dense(const Eigen::VectorXd& beta_hat, const Eigen::VectorXd& beta, double eps);
RcppExport SEXP _TRexSelector_rcpp_compute_tpp_dense(SEXP beta_hatSEXP, SEXP betaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta_hat(beta_hatSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_compute_tpp_dense(beta_hat, beta, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TRexSelector_rcpp_agglomerative_cluster", (DL_FUNC) &_TRexSelector_rcpp_agglomerative_cluster, 4},
    {"_TRexSelector_rcpp_cut_tree", (DL_FUNC) &_TRexSelector_rcpp_cut_tree, 3},
    {"_TRexSelector_zscore_scaler_create", (DL_FUNC) &_TRexSelector_zscore_scaler_create, 2},
    {"_TRexSelector_zscore_scaler_fit", (DL_FUNC) &_TRexSelector_zscore_scaler_fit, 3},
    {"_TRexSelector_zscore_scaler_transform_inplace", (DL_FUNC) &_TRexSelector_zscore_scaler_transform_inplace, 2},
    {"_TRexSelector_zscore_scaler_inverse_transform_inplace", (DL_FUNC) &_TRexSelector_zscore_scaler_inverse_transform_inplace, 2},
    {"_TRexSelector_zscore_scaler_is_fitted", (DL_FUNC) &_TRexSelector_zscore_scaler_is_fitted, 1},
    {"_TRexSelector_zscore_scaler_get_dropped_indices", (DL_FUNC) &_TRexSelector_zscore_scaler_get_dropped_indices, 1},
    {"_TRexSelector_zscore_scaler_get_with_mean", (DL_FUNC) &_TRexSelector_zscore_scaler_get_with_mean, 1},
    {"_TRexSelector_zscore_scaler_get_with_std", (DL_FUNC) &_TRexSelector_zscore_scaler_get_with_std, 1},
    {"_TRexSelector_zscore_scaler_get_means", (DL_FUNC) &_TRexSelector_zscore_scaler_get_means, 1},
    {"_TRexSelector_zscore_scaler_get_scales", (DL_FUNC) &_TRexSelector_zscore_scaler_get_scales, 1},
    {"_TRexSelector_zscore_scaler_save", (DL_FUNC) &_TRexSelector_zscore_scaler_save, 2},
    {"_TRexSelector_zscore_scaler_load", (DL_FUNC) &_TRexSelector_zscore_scaler_load, 2},
    {"_TRexSelector_lpnorm_scaler_create", (DL_FUNC) &_TRexSelector_lpnorm_scaler_create, 2},
    {"_TRexSelector_lpnorm_scaler_fit", (DL_FUNC) &_TRexSelector_lpnorm_scaler_fit, 3},
    {"_TRexSelector_lpnorm_scaler_transform_inplace", (DL_FUNC) &_TRexSelector_lpnorm_scaler_transform_inplace, 2},
    {"_TRexSelector_lpnorm_scaler_inverse_transform_inplace", (DL_FUNC) &_TRexSelector_lpnorm_scaler_inverse_transform_inplace, 2},
    {"_TRexSelector_lpnorm_scaler_is_fitted", (DL_FUNC) &_TRexSelector_lpnorm_scaler_is_fitted, 1},
    {"_TRexSelector_lpnorm_scaler_get_dropped_indices", (DL_FUNC) &_TRexSelector_lpnorm_scaler_get_dropped_indices, 1},
    {"_TRexSelector_lpnorm_scaler_get_means", (DL_FUNC) &_TRexSelector_lpnorm_scaler_get_means, 1},
    {"_TRexSelector_lpnorm_scaler_get_scales", (DL_FUNC) &_TRexSelector_lpnorm_scaler_get_scales, 1},
    {"_TRexSelector_lpnorm_scaler_get_with_mean", (DL_FUNC) &_TRexSelector_lpnorm_scaler_get_with_mean, 1},
    {"_TRexSelector_lpnorm_scaler_get_with_norm", (DL_FUNC) &_TRexSelector_lpnorm_scaler_get_with_norm, 1},
    {"_TRexSelector_lpnorm_scaler_get_norm_type", (DL_FUNC) &_TRexSelector_lpnorm_scaler_get_norm_type, 1},
    {"_TRexSelector_lpnorm_scaler_save", (DL_FUNC) &_TRexSelector_lpnorm_scaler_save, 2},
    {"_TRexSelector_lpnorm_scaler_load", (DL_FUNC) &_TRexSelector_lpnorm_scaler_load, 2},
    {"_TRexSelector_ridge_gcv_create", (DL_FUNC) &_TRexSelector_ridge_gcv_create, 0},
    {"_TRexSelector_ridge_gcv_fit", (DL_FUNC) &_TRexSelector_ridge_gcv_fit, 3},
    {"_TRexSelector_ridge_gcv_solve", (DL_FUNC) &_TRexSelector_ridge_gcv_solve, 2},
    {"_TRexSelector_ridge_gcv_gcv_score", (DL_FUNC) &_TRexSelector_ridge_gcv_gcv_score, 2},
    {"_TRexSelector_ridge_gcv_predict", (DL_FUNC) &_TRexSelector_ridge_gcv_predict, 3},
    {"_TRexSelector_ridge_gcv_predict_path", (DL_FUNC) &_TRexSelector_ridge_gcv_predict_path, 3},
    {"_TRexSelector_ridge_gcv_default_lambda_grid", (DL_FUNC) &_TRexSelector_ridge_gcv_default_lambda_grid, 3},
    {"_TRexSelector_ridge_gcv_n_samples", (DL_FUNC) &_TRexSelector_ridge_gcv_n_samples, 1},
    {"_TRexSelector_ridge_gcv_n_features", (DL_FUNC) &_TRexSelector_ridge_gcv_n_features, 1},
    {"_TRexSelector_ridge_gcv_rank", (DL_FUNC) &_TRexSelector_ridge_gcv_rank, 1},
    {"_TRexSelector_ridge_gcv_solve_path", (DL_FUNC) &_TRexSelector_ridge_gcv_solve_path, 2},
    {"_TRexSelector_ridge_gcv_optimal", (DL_FUNC) &_TRexSelector_ridge_gcv_optimal, 3},
    {"_TRexSelector_ridge_cv_create", (DL_FUNC) &_TRexSelector_ridge_cv_create, 0},
    {"_TRexSelector_ridge_cv_fit", (DL_FUNC) &_TRexSelector_ridge_cv_fit, 7},
    {"_TRexSelector_ridge_cv_min", (DL_FUNC) &_TRexSelector_ridge_cv_min, 1},
    {"_TRexSelector_ridge_cv_1se", (DL_FUNC) &_TRexSelector_ridge_cv_1se, 1},
    {"_TRexSelector_ridge_cv_index_min", (DL_FUNC) &_TRexSelector_ridge_cv_index_min, 1},
    {"_TRexSelector_ridge_cv_index_1se", (DL_FUNC) &_TRexSelector_ridge_cv_index_1se, 1},
    {"_TRexSelector_ridge_cv_get_lambdas", (DL_FUNC) &_TRexSelector_ridge_cv_get_lambdas, 1},
    {"_TRexSelector_ridge_cv_get_cv_errors", (DL_FUNC) &_TRexSelector_ridge_cv_get_cv_errors, 1},
    {"_TRexSelector_ridge_cv_get_cv_std", (DL_FUNC) &_TRexSelector_ridge_cv_get_cv_std, 1},
    {"_TRexSelector_trex_selector_create", (DL_FUNC) &_TRexSelector_trex_selector_create, 6},
    {"_TRexSelector_trex_selector_mmap_create", (DL_FUNC) &_TRexSelector_trex_selector_mmap_create, 6},
    {"_TRexSelector_trex_selector_select", (DL_FUNC) &_TRexSelector_trex_selector_select, 1},
    {"_TRexSelector_trex_selector_get_selected_indices", (DL_FUNC) &_TRexSelector_trex_selector_get_selected_indices, 1},
    {"_TRexSelector_trex_da_create", (DL_FUNC) &_TRexSelector_trex_da_create, 7},
    {"_TRexSelector_trex_da_mmap_create", (DL_FUNC) &_TRexSelector_trex_da_mmap_create, 7},
    {"_TRexSelector_trex_da_select", (DL_FUNC) &_TRexSelector_trex_da_select, 1},
    {"_TRexSelector_trex_da_get_selected_indices", (DL_FUNC) &_TRexSelector_trex_da_get_selected_indices, 1},
    {"_TRexSelector_tsolver_lars_create", (DL_FUNC) &_TRexSelector_tsolver_lars_create, 3},
    {"_TRexSelector_tsolver_omp_create", (DL_FUNC) &_TRexSelector_tsolver_omp_create, 3},
    {"_TRexSelector_tsolver_lars_mmap_create", (DL_FUNC) &_TRexSelector_tsolver_lars_mmap_create, 3},
    {"_TRexSelector_tsolver_omp_mmap_create", (DL_FUNC) &_TRexSelector_tsolver_omp_mmap_create, 3},
    {"_TRexSelector_tsolver_execute_step", (DL_FUNC) &_TRexSelector_tsolver_execute_step, 3},
    {"_TRexSelector_tsolver_get_beta", (DL_FUNC) &_TRexSelector_tsolver_get_beta, 2},
    {"_TRexSelector_tsolver_get_cp", (DL_FUNC) &_TRexSelector_tsolver_get_cp, 1},
    {"_TRexSelector_tsolver_get_rss", (DL_FUNC) &_TRexSelector_tsolver_get_rss, 1},
    {"_TRexSelector_tsolver_get_r2", (DL_FUNC) &_TRexSelector_tsolver_get_r2, 1},
    {"_TRexSelector_tsolver_get_dof", (DL_FUNC) &_TRexSelector_tsolver_get_dof, 1},
    {"_TRexSelector_tsolver_get_actives", (DL_FUNC) &_TRexSelector_tsolver_get_actives, 1},
    {"_TRexSelector_tsolver_get_inactives", (DL_FUNC) &_TRexSelector_tsolver_get_inactives, 1},
    {"_TRexSelector_tsolver_get_intercept", (DL_FUNC) &_TRexSelector_tsolver_get_intercept, 2},
    {"_TRexSelector_tsolver_save", (DL_FUNC) &_TRexSelector_tsolver_save, 2},
    {"_TRexSelector_tsolver_load", (DL_FUNC) &_TRexSelector_tsolver_load, 2},
    {"_TRexSelector_mmap_matrix_create", (DL_FUNC) &_TRexSelector_mmap_matrix_create, 4},
    {"_TRexSelector_mmap_matrix_to_r_matrix", (DL_FUNC) &_TRexSelector_mmap_matrix_to_r_matrix, 1},
    {"_TRexSelector_convert_to_memory_mapped_matrix", (DL_FUNC) &_TRexSelector_convert_to_memory_mapped_matrix, 2},
    {"_TRexSelector_mmap_matrix_rows", (DL_FUNC) &_TRexSelector_mmap_matrix_rows, 1},
    {"_TRexSelector_mmap_matrix_cols", (DL_FUNC) &_TRexSelector_mmap_matrix_cols, 1},
    {"_TRexSelector_mmap_matrix_size", (DL_FUNC) &_TRexSelector_mmap_matrix_size, 1},
    {"_TRexSelector_mmap_matrix_read_range", (DL_FUNC) &_TRexSelector_mmap_matrix_read_range, 5},
    {"_TRexSelector_rcpp_compute_fdp", (DL_FUNC) &_TRexSelector_rcpp_compute_fdp, 2},
    {"_TRexSelector_rcpp_compute_tpp", (DL_FUNC) &_TRexSelector_rcpp_compute_tpp, 2},
    {"_TRexSelector_rcpp_compute_precision", (DL_FUNC) &_TRexSelector_rcpp_compute_precision, 2},
    {"_TRexSelector_rcpp_compute_recall", (DL_FUNC) &_TRexSelector_rcpp_compute_recall, 2},
    {"_TRexSelector_rcpp_compute_fdp_dense", (DL_FUNC) &_TRexSelector_rcpp_compute_fdp_dense, 3},
    {"_TRexSelector_rcpp_compute_tpp_dense", (DL_FUNC) &_TRexSelector_rcpp_compute_tpp_dense, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_TRexSelector(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, (Rboolean)FALSE);
}
