# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Rcpp Agglomerative Clustering
#'
#' @description Perform agglomerative clustering
#'
#' @param data Matrix of shape (N, Features).
#' @param method_idx Linkage method index (0=Ward, 1=Average, 2=Complete, 3=Single, 4=WPGMA,
#'                      5=Median, 6=Centroid)
#' @param metric_idx Distance metric index (0=Euclid, 1=Corr, 2=Manhattan, 3=CorrLSHF, 4=CorrLSHA)
#' @param use_mmap Boolean flag for memory mapping
#'
#' @return A linkage matrix
#'
#' @noRd
rcpp_agglomerative_cluster <- function(data, method_idx, metric_idx, use_mmap = FALSE) {
    .Call(`_TRexSelector_rcpp_agglomerative_cluster`, data, method_idx, metric_idx, use_mmap)
}

#' @title Rcpp Cut Tree
#'
#' @description Cut a linkage matrix into flat clusters
#'
#' @param linkage Linkage matrix from agglomerative_cluster
#' @param num_orig_objs Original number of rows in dataset
#' @param num_clusters Desired number of flat clusters
#'
#' @return Integer vector of cluster indices
#'
#' @noRd
rcpp_cut_tree <- function(linkage, num_orig_objs, num_clusters) {
    .Call(`_TRexSelector_rcpp_cut_tree`, linkage, num_orig_objs, num_clusters)
}

#' @title Create ZScoreScaler
#'
#' @param with_mean Center data
#' @param with_std Scale data
#' @return XPtr to ZScoreScaler
#' @noRd
zscore_scaler_create <- function(with_mean, with_std) {
    .Call(`_TRexSelector_zscore_scaler_create`, with_mean, with_std)
}

#' @title Fit ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param X Matrix to fit
#' @param threshold Numerical stability threshold
#' @noRd
zscore_scaler_fit <- function(ptr, X, threshold = 1e-12) {
    invisible(.Call(`_TRexSelector_zscore_scaler_fit`, ptr, X, threshold))
}

#' @title Transform Inplace ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param X Matrix to transform
#' @noRd
zscore_scaler_transform_inplace <- function(ptr, X) {
    invisible(.Call(`_TRexSelector_zscore_scaler_transform_inplace`, ptr, X))
}

#' @title Inverse Transform Inplace ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param X Matrix to transform
#' @noRd
zscore_scaler_inverse_transform_inplace <- function(ptr, X) {
    invisible(.Call(`_TRexSelector_zscore_scaler_inverse_transform_inplace`, ptr, X))
}

#' @title Check if ZScoreScaler is fitted
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Boolean indicating fit status
#' @noRd
zscore_scaler_is_fitted <- function(ptr) {
    .Call(`_TRexSelector_zscore_scaler_is_fitted`, ptr)
}

#' @title Get dropped indices from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Vector of dropped indices
#' @noRd
zscore_scaler_get_dropped_indices <- function(ptr) {
    .Call(`_TRexSelector_zscore_scaler_get_dropped_indices`, ptr)
}

#' @title Get with_mean flag from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Boolean with_mean
#' @noRd
zscore_scaler_get_with_mean <- function(ptr) {
    .Call(`_TRexSelector_zscore_scaler_get_with_mean`, ptr)
}

#' @title Get with_std flag from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Boolean with_std
#' @noRd
zscore_scaler_get_with_std <- function(ptr) {
    .Call(`_TRexSelector_zscore_scaler_get_with_std`, ptr)
}

#' @title Get means from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Vector of means
#' @noRd
zscore_scaler_get_means <- function(ptr) {
    .Call(`_TRexSelector_zscore_scaler_get_means`, ptr)
}

#' @title Get scales from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Vector of scales
#' @noRd
zscore_scaler_get_scales <- function(ptr) {
    .Call(`_TRexSelector_zscore_scaler_get_scales`, ptr)
}

#' @title Save ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param filename Output filename
#' @noRd
zscore_scaler_save <- function(ptr, filename) {
    invisible(.Call(`_TRexSelector_zscore_scaler_save`, ptr, filename))
}

#' @title Load ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param filename Input filename
#' @noRd
zscore_scaler_load <- function(ptr, filename) {
    invisible(.Call(`_TRexSelector_zscore_scaler_load`, ptr, filename))
}

#' @title Create LpNormScaler
#'
#' @param norm_type Type of norm (1 for L1, 2 for L2)
#' @param with_mean Center data
#' @return XPtr to LpNormScaler
#' @noRd
lpnorm_scaler_create <- function(norm_type, with_mean) {
    .Call(`_TRexSelector_lpnorm_scaler_create`, norm_type, with_mean)
}

#' @title Fit LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param X Matrix to fit
#' @param threshold Numerical stability threshold
#' @noRd
lpnorm_scaler_fit <- function(ptr, X, threshold = 1e-12) {
    invisible(.Call(`_TRexSelector_lpnorm_scaler_fit`, ptr, X, threshold))
}

#' @title Transform Inplace LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param X Matrix to transform
#' @noRd
lpnorm_scaler_transform_inplace <- function(ptr, X) {
    invisible(.Call(`_TRexSelector_lpnorm_scaler_transform_inplace`, ptr, X))
}

#' @title Inverse Transform Inplace LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param X Matrix to transform
#' @noRd
lpnorm_scaler_inverse_transform_inplace <- function(ptr, X) {
    invisible(.Call(`_TRexSelector_lpnorm_scaler_inverse_transform_inplace`, ptr, X))
}

#' @title Check if LpNormScaler is fitted
#'
#' @param ptr XPtr to LpNormScaler
#' @return Boolean indicating fit status
#' @noRd
lpnorm_scaler_is_fitted <- function(ptr) {
    .Call(`_TRexSelector_lpnorm_scaler_is_fitted`, ptr)
}

#' @title Get dropped indices from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Vector of dropped indices
#' @noRd
lpnorm_scaler_get_dropped_indices <- function(ptr) {
    .Call(`_TRexSelector_lpnorm_scaler_get_dropped_indices`, ptr)
}

#' @title Get means from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Vector of means
#' @noRd
lpnorm_scaler_get_means <- function(ptr) {
    .Call(`_TRexSelector_lpnorm_scaler_get_means`, ptr)
}

#' @title Get scales from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Vector of scales
#' @noRd
lpnorm_scaler_get_scales <- function(ptr) {
    .Call(`_TRexSelector_lpnorm_scaler_get_scales`, ptr)
}

#' @title Get with_mean flag from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Boolean with_mean
#' @noRd
lpnorm_scaler_get_with_mean <- function(ptr) {
    .Call(`_TRexSelector_lpnorm_scaler_get_with_mean`, ptr)
}

#' @title Get with_norm flag from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Boolean with_norm
#' @noRd
lpnorm_scaler_get_with_norm <- function(ptr) {
    .Call(`_TRexSelector_lpnorm_scaler_get_with_norm`, ptr)
}

#' @title Get norm type from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Integer norm type
#' @noRd
lpnorm_scaler_get_norm_type <- function(ptr) {
    .Call(`_TRexSelector_lpnorm_scaler_get_norm_type`, ptr)
}

#' @title Save LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param filename Output filename
#' @noRd
lpnorm_scaler_save <- function(ptr, filename) {
    invisible(.Call(`_TRexSelector_lpnorm_scaler_save`, ptr, filename))
}

#' @title Load LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param filename Input filename
#' @noRd
lpnorm_scaler_load <- function(ptr, filename) {
    invisible(.Call(`_TRexSelector_lpnorm_scaler_load`, ptr, filename))
}

#' @title Create Ridge GCV
#'
#' @return XPtr to ridge_gcv
#' @noRd
ridge_gcv_create <- function() {
    .Call(`_TRexSelector_ridge_gcv_create`)
}

#' @title Fit Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param X Design matrix
#' @param y Response vector
#' @noRd
ridge_gcv_fit <- function(ptr, X, y) {
    invisible(.Call(`_TRexSelector_ridge_gcv_fit`, ptr, X, y))
}

#' @title Solve Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param lambda_val Lambda value
#' @return Coefficients
#' @noRd
ridge_gcv_solve <- function(ptr, lambda_val) {
    .Call(`_TRexSelector_ridge_gcv_solve`, ptr, lambda_val)
}

#' @title Get GCV Score
#'
#' @param ptr XPtr to ridge_gcv
#' @param lambda_val Lambda value
#' @return GCV score
#' @noRd
ridge_gcv_gcv_score <- function(ptr, lambda_val) {
    .Call(`_TRexSelector_ridge_gcv_gcv_score`, ptr, lambda_val)
}

#' @title Predict with Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param X_new New data
#' @param lambda_val Lambda value
#' @return Predictions
#' @noRd
ridge_gcv_predict <- function(ptr, X_new, lambda_val) {
    .Call(`_TRexSelector_ridge_gcv_predict`, ptr, X_new, lambda_val)
}

#' @title Predict Path with Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param X_new New data
#' @param lambdas Lambda values
#' @return Predictions
#' @noRd
ridge_gcv_predict_path <- function(ptr, X_new, lambdas) {
    .Call(`_TRexSelector_ridge_gcv_predict_path`, ptr, X_new, lambdas)
}

#' @title Get Default Lambda Grid from Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param num_lambda Number of lambdas
#' @param ratio Ratio
#' @return Lambda grid
#' @noRd
ridge_gcv_default_lambda_grid <- function(ptr, num_lambda, ratio) {
    .Call(`_TRexSelector_ridge_gcv_default_lambda_grid`, ptr, num_lambda, ratio)
}

#' @title Get number of samples from Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @return Number of samples
#' @noRd
ridge_gcv_n_samples <- function(ptr) {
    .Call(`_TRexSelector_ridge_gcv_n_samples`, ptr)
}

#' @title Get number of features from Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @return Number of features
#' @noRd
ridge_gcv_n_features <- function(ptr) {
    .Call(`_TRexSelector_ridge_gcv_n_features`, ptr)
}

#' @title Get rank from Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @return Rank
#' @noRd
ridge_gcv_rank <- function(ptr) {
    .Call(`_TRexSelector_ridge_gcv_rank`, ptr)
}

#' @title Solve Path Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param lambdas Lambda values
#' @return List of path results
#' @noRd
ridge_gcv_solve_path <- function(ptr, lambdas) {
    .Call(`_TRexSelector_ridge_gcv_solve_path`, ptr, lambdas)
}

#' @title Get optimal lambda from Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param num_grid Number of grid points
#' @param tol Tolerance
#' @return Optimal GCV lambda
#' @noRd
ridge_gcv_optimal <- function(ptr, num_grid, tol) {
    .Call(`_TRexSelector_ridge_gcv_optimal`, ptr, num_grid, tol)
}

#' @title Create Ridge CV
#'
#' @return XPtr to ridge_cv
#' @noRd
ridge_cv_create <- function() {
    .Call(`_TRexSelector_ridge_cv_create`)
}

#' @title Fit Ridge CV
#'
#' @param ptr XPtr to ridge_cv
#' @param X Design matrix
#' @param y Response vector
#' @param num_folds Number of folds
#' @param n_lambda Number of lambdas
#' @param lambda_ratio Lambda ratio
#' @param seed Random seed
#' @noRd
ridge_cv_fit <- function(ptr, X, y, num_folds, n_lambda, lambda_ratio, seed) {
    invisible(.Call(`_TRexSelector_ridge_cv_fit`, ptr, X, y, num_folds, n_lambda, lambda_ratio, seed))
}

#' @title Get min CV error
#'
#' @param ptr XPtr to ridge_cv
#' @return Min CV error
#' @noRd
ridge_cv_min <- function(ptr) {
    .Call(`_TRexSelector_ridge_cv_min`, ptr)
}

#' @title Get 1SE CV error
#'
#' @param ptr XPtr to ridge_cv
#' @return 1SE CV error
#' @noRd
ridge_cv_1se <- function(ptr) {
    .Call(`_TRexSelector_ridge_cv_1se`, ptr)
}

#' @title Get min index
#'
#' @param ptr XPtr to ridge_cv
#' @return Index of min CV error
#' @noRd
ridge_cv_index_min <- function(ptr) {
    .Call(`_TRexSelector_ridge_cv_index_min`, ptr)
}

#' @title Get 1SE index
#'
#' @param ptr XPtr to ridge_cv
#' @return Index of 1SE CV error
#' @noRd
ridge_cv_index_1se <- function(ptr) {
    .Call(`_TRexSelector_ridge_cv_index_1se`, ptr)
}

#' @title Get Lambdas
#'
#' @param ptr XPtr to ridge_cv
#' @return Vector of lambdas
#' @noRd
ridge_cv_get_lambdas <- function(ptr) {
    .Call(`_TRexSelector_ridge_cv_get_lambdas`, ptr)
}

#' @title Get CV Errors
#'
#' @param ptr XPtr to ridge_cv
#' @return Vector of CV errors
#' @noRd
ridge_cv_get_cv_errors <- function(ptr) {
    .Call(`_TRexSelector_ridge_cv_get_cv_errors`, ptr)
}

#' @title Get CV Standard Errors
#'
#' @param ptr XPtr to ridge_cv
#' @return Vector of CV standard errors
#' @noRd
ridge_cv_get_cv_std <- function(ptr) {
    .Call(`_TRexSelector_ridge_cv_get_cv_std`, ptr)
}

#' @title Create RTRexBiobankScreeningSelector 1D
#' @noRd
trex_biobank_screening_1d_create <- function(X, y, biobank_control_list, screen_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelector_trex_biobank_screening_1d_create`, X, y, biobank_control_list, screen_control_list, trex_control_list, seed, verbose)
}

#' @title Create RTRexBiobankScreeningSelector 2D
#' @noRd
trex_biobank_screening_2d_create <- function(X, Y, biobank_control_list, screen_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelector_trex_biobank_screening_2d_create`, X, Y, biobank_control_list, screen_control_list, trex_control_list, seed, verbose)
}

#' @title Screen Single Phenotype
#' @noRd
trex_biobank_screening_screen_phenotype <- function(r_ptr) {
    .Call(`_TRexSelector_trex_biobank_screening_screen_phenotype`, r_ptr)
}

#' @title Screen Multiple Phenotypes
#' @noRd
trex_biobank_screening_screen_phenotypes <- function(r_ptr) {
    .Call(`_TRexSelector_trex_biobank_screening_screen_phenotypes`, r_ptr)
}

#' @title Create TRexDASelector
#' @noRd
trex_da_create <- function(X, y, tFDR, da_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelector_trex_da_create`, X, y, tFDR, da_control_list, trex_control_list, seed, verbose)
}

#' @title Create TRexDASelector from mmap
#' @noRd
trex_da_mmap_create <- function(X_ptr, y, tFDR, da_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelector_trex_da_mmap_create`, X_ptr, y, tFDR, da_control_list, trex_control_list, seed, verbose)
}

#' @title Run TRexDASelector
#' @noRd
trex_da_select <- function(r_ptr) {
    invisible(.Call(`_TRexSelector_trex_da_select`, r_ptr))
}

#' @title Cast DA pointer to Base pointer
#' @noRd
trex_da_to_base_ptr <- function(r_ptr) {
    .Call(`_TRexSelector_trex_da_to_base_ptr`, r_ptr)
}

#' @title Get DA Rho Threshold
#' @noRd
trex_da_get_rho_thresh <- function(r_ptr) {
    .Call(`_TRexSelector_trex_da_get_rho_thresh`, r_ptr)
}

#' @title Get DA Rho Grid
#' @noRd
trex_da_get_rho_grid <- function(r_ptr) {
    .Call(`_TRexSelector_trex_da_get_rho_grid`, r_ptr)
}

#' @title Get DA Method String
#' @noRd
trex_da_get_method_string <- function(r_ptr) {
    .Call(`_TRexSelector_trex_da_get_method_string`, r_ptr)
}

#' @title Get DA Cor Coef
#' @noRd
trex_da_get_cor_coef <- function(r_ptr) {
    .Call(`_TRexSelector_trex_da_get_cor_coef`, r_ptr)
}

#' @title Get DA FDP Hat Array BT
#' @noRd
trex_da_get_fdp_hat_array_bt <- function(r_ptr) {
    .Call(`_TRexSelector_trex_da_get_fdp_hat_array_bt`, r_ptr)
}

#' @title Get DA Phi Array BT
#' @noRd
trex_da_get_phi_array_bt <- function(r_ptr) {
    .Call(`_TRexSelector_trex_da_get_phi_array_bt`, r_ptr)
}

#' @title Get DA R Array BT
#' @noRd
trex_da_get_r_array_bt <- function(r_ptr) {
    .Call(`_TRexSelector_trex_da_get_r_array_bt`, r_ptr)
}

#' @title Create TRexGVSSelector
#' @noRd
trex_gvs_create <- function(X, y, tFDR, gvs_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelector_trex_gvs_create`, X, y, tFDR, gvs_control_list, trex_control_list, seed, verbose)
}

#' @title Create TRexGVSSelector from MemoryMappedMatrix
#' @noRd
trex_gvs_mmap_create <- function(X_ptr, y, tFDR, gvs_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelector_trex_gvs_mmap_create`, X_ptr, y, tFDR, gvs_control_list, trex_control_list, seed, verbose)
}

#' @title Run TRexGVSSelector
#' @noRd
trex_gvs_select <- function(r_ptr) {
    invisible(.Call(`_TRexSelector_trex_gvs_select`, r_ptr))
}

#' @title Get lambda2_used
#' @noRd
trex_gvs_get_lambda2_used <- function(r_ptr) {
    .Call(`_TRexSelector_trex_gvs_get_lambda2_used`, r_ptr)
}

#' @title Get gvs_type
#' @noRd
trex_gvs_get_gvs_type <- function(r_ptr) {
    .Call(`_TRexSelector_trex_gvs_get_gvs_type`, r_ptr)
}

#' @title Get max_clusters
#' @noRd
trex_gvs_get_max_clusters <- function(r_ptr) {
    .Call(`_TRexSelector_trex_gvs_get_max_clusters`, r_ptr)
}

#' @title Get Selected Indices
#' @noRd
trex_gvs_get_selected_indices <- function(r_ptr) {
    .Call(`_TRexSelector_trex_gvs_get_selected_indices`, r_ptr)
}

#' @title Create RTRexScreeningSelector
#'
#' @details Instantiates a Screen-TRex selector object.
#'
#' @param X Design matrix (n x p).
#' @param y Response vector (n).
#' @param screen_control_list List of Screen-TRex specific control parameters.
#' @param trex_control_list List of general T-Rex control parameters.
#' @param seed Random seed for reproducibility.
#' @param verbose Whether to print progress messages.
#'
#' @return XPtr to RTRexScreeningSelector instance.
#'
#' @noRd
#'
trex_screening_create <- function(X, y, screen_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelector_trex_screening_create`, X, y, screen_control_list, trex_control_list, seed, verbose)
}

#' @title Create RTRexScreeningSelector from mmap
#'
#' @details Instantiates a Screen-TRex selector object using a memory-mapped design matrix
#'
#' @param X_ptr Pointer to MemoryMappedMatrix for the design matrix.
#' @param y Response vector (n).
#' @param screen_control_list List of Screen-TRex specific control parameters.
#' @param trex_control_list List of general T-Rex control parameters.
#' @param seed Random seed for reproducibility.
#' @param verbose Whether to print progress messages.
#'
#' @noRd
#'
trex_screening_mmap_create <- function(X_ptr, y, screen_control_list, trex_control_list, seed, verbose) {
    .Call(`_TRexSelector_trex_screening_mmap_create`, X_ptr, y, screen_control_list, trex_control_list, seed, verbose)
}

#' @title Run RTRexScreeningSelector
#'
#' @details Executes the selection procedure of the Screen-TRex selector.
#'
#' @param r_ptr Pointer to the RTRexScreeningSelector instance
#'
#' @noRd
#'
trex_screening_select <- function(r_ptr) {
    invisible(.Call(`_TRexSelector_trex_screening_select`, r_ptr))
}

#' @title Get estimated_FDR
#' @noRd
trex_screening_get_estimated_fdr <- function(r_ptr) {
    .Call(`_TRexSelector_trex_screening_get_estimated_fdr`, r_ptr)
}

#' @title Get used_bootstrap
#' @noRd
trex_screening_get_used_bootstrap <- function(r_ptr) {
    .Call(`_TRexSelector_trex_screening_get_used_bootstrap`, r_ptr)
}

#' @title Get confidence_level
#' @noRd
trex_screening_get_confidence_level <- function(r_ptr) {
    .Call(`_TRexSelector_trex_screening_get_confidence_level`, r_ptr)
}

#' @title Get estimated_correlation
#' @noRd
trex_screening_get_estimated_correlation <- function(r_ptr) {
    .Call(`_TRexSelector_trex_screening_get_estimated_correlation`, r_ptr)
}

#' @title Get beta_mat
#' @noRd
trex_screening_get_beta_mat <- function(r_ptr) {
    .Call(`_TRexSelector_trex_screening_get_beta_mat`, r_ptr)
}

#' @title Get dummy_betas
#' @noRd
trex_screening_get_dummy_betas <- function(r_ptr) {
    .Call(`_TRexSelector_trex_screening_get_dummy_betas`, r_ptr)
}

#' @title Get Selected Indices
#'
#' @details Retrieves the indices of the selected variables from the Screen-TRex selector.
#'
#' @param r_ptr Pointer to the RTRexScreeningSelector instance.
#'
#' @noRd
#'
trex_screening_get_selected_indices <- function(r_ptr) {
    .Call(`_TRexSelector_trex_screening_get_selected_indices`, r_ptr)
}

#' @title Create TRexSelector
#'
#' @param X Design matrix (n × p).
#' @param y Response vector (n).
#' @param tFDR Target FDR level (default: 0.1).
#' @param control List of control parameters (see details).
#' @param seed Random seed (default: -1).
#' @param verbose Whether to print progress (default: TRUE).
#'
#' @noRd
trex_selector_create <- function(X, y, tFDR, control_list, seed, verbose) {
    .Call(`_TRexSelector_trex_selector_create`, X, y, tFDR, control_list, seed, verbose)
}

#' @title Create TRexSelector from mmap
#'
#' @param X_ptr Pointer to MemoryMappedMatrix (n × p).
#' @param y Response vector (n).
#' @param tFDR Target FDR level (default: 0.1).
#' @param control List of control parameters (see details).
#' @param seed Random seed (default: -1).
#' @param verbose Whether to print progress (default: TRUE).
#'
#' @noRd
trex_selector_mmap_create <- function(X_ptr, y, tFDR, control_list, seed, verbose) {
    .Call(`_TRexSelector_trex_selector_mmap_create`, X_ptr, y, tFDR, control_list, seed, verbose)
}

#' @title Run TRexSelector
#'
#' @param r_ptr Pointer to RTRexSelector instance.
#'
#' @noRd
trex_selector_select <- function(r_ptr) {
    invisible(.Call(`_TRexSelector_trex_selector_select`, r_ptr))
}

#' @title Get Selected Variables
#'
#' @param r_ptr Pointer to RTRexSelector instance.
#'
#' @noRd
trex_selector_get_selected_var <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_selected_var`, r_ptr)
}

#' @title Get Selected Indices
#'
#' @param r_ptr Pointer to RTRexSelector instance.
#'
#' @noRd
trex_selector_get_selected_indices <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_selected_indices`, r_ptr)
}

#' @title Get Voting Threshold
#' @noRd
trex_selector_get_voting_threshold <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_voting_threshold`, r_ptr)
}

#' @title Get Stopping Time T
#' @noRd
trex_selector_get_t_stop <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_t_stop`, r_ptr)
}

#' @title Get Dummy Multiplier L
#' @noRd
trex_selector_get_dummy_multiplier_l <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_dummy_multiplier_l`, r_ptr)
}

#' @title Get Voting Grid
#' @noRd
trex_selector_get_voting_grid <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_voting_grid`, r_ptr)
}

#' @title Get FDP Hat Matrix
#' @noRd
trex_selector_get_fdp_hat_mat <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_fdp_hat_mat`, r_ptr)
}

#' @title Get Phi Matrix
#' @noRd
trex_selector_get_phi_mat <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_phi_mat`, r_ptr)
}

#' @title Get R Matrix
#' @noRd
trex_selector_get_r_mat <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_r_mat`, r_ptr)
}

#' @title Get Phi Prime
#' @noRd
trex_selector_get_phi_prime <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_phi_prime`, r_ptr)
}

#' @title Get X Means
#' @noRd
trex_selector_get_x_means <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_x_means`, r_ptr)
}

#' @title Get X L2 Norms
#' @noRd
trex_selector_get_x_l2_norms <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_x_l2_norms`, r_ptr)
}

#' @title Get y Mean
#' @noRd
trex_selector_get_y_mean <- function(r_ptr) {
    .Call(`_TRexSelector_trex_selector_get_y_mean`, r_ptr)
}

#' @title Create LARS Solver
#'
#' @param X Design matrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolverRcpp
#' @noRd
tsolver_lars_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_lars_create`, X, D, y, normalize, intercept, verbose)
}

#' @title Create OMP Solver
#'
#' @param X Design matrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolverRcpp
#' @noRd
tsolver_omp_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_omp_create`, X, D, y, normalize, intercept, verbose)
}

#' @title Create LARS Solver with Memory Mapped Matrix
#'
#' @param X_ptr Pointer to MemoryMappedMatrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolverRcpp
#' @noRd
tsolver_lars_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_lars_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @title Create OMP Solver with Memory Mapped Matrix
#'
#' @param X_ptr Pointer to MemoryMappedMatrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolverRcpp
#' @noRd
tsolver_omp_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_omp_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tlasso_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tlasso_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tstepwise_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tstepwise_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tenet_create <- function(X, D, y, lambda2, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tenet_create`, X, D, y, lambda2, normalize, intercept, verbose)
}

#' @noRd
tsolver_tstagewise_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tstagewise_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tgp_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tgp_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tacgp_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tacgp_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tmp_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tmp_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tools_create <- function(X, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tools_create`, X, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tncgmp_create <- function(X, D, y, variant = 0L, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tncgmp_create`, X, D, y, variant, normalize, intercept, verbose)
}

#' @noRd
tsolver_tafs_create <- function(X, D, y, rho = 1.0, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tafs_create`, X, D, y, rho, normalize, intercept, verbose)
}

#' @noRd
tsolver_tlasso_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tlasso_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tstepwise_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tstepwise_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tenet_mmap_create <- function(X_ptr, D, y, lambda2, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tenet_mmap_create`, X_ptr, D, y, lambda2, normalize, intercept, verbose)
}

#' @noRd
tsolver_tstagewise_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tstagewise_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tgp_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tgp_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tacgp_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tacgp_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tmp_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tmp_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tools_mmap_create <- function(X_ptr, D, y, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tools_mmap_create`, X_ptr, D, y, normalize, intercept, verbose)
}

#' @noRd
tsolver_tncgmp_mmap_create <- function(X_ptr, D, y, variant = 0L, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tncgmp_mmap_create`, X_ptr, D, y, variant, normalize, intercept, verbose)
}

#' @noRd
tsolver_tafs_mmap_create <- function(X_ptr, D, y, rho = 1.0, normalize = TRUE, intercept = TRUE, verbose = FALSE) {
    .Call(`_TRexSelector_tsolver_tafs_mmap_create`, X_ptr, D, y, rho, normalize, intercept, verbose)
}

#' @title Execute Step in TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @param T_stop Number of steps to compute
#' @param early_stop Whether to stop early based on constraints
#' @noRd
tsolver_execute_step <- function(ptr, T_stop, early_stop = TRUE) {
    invisible(.Call(`_TRexSelector_tsolver_execute_step`, ptr, T_stop, early_stop))
}

#' @title Get Beta from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @param step Step to retrieve beta for
#'
#' @return Beta vector
#' @noRd
tsolver_get_beta <- function(ptr, step = -1L) {
    .Call(`_TRexSelector_tsolver_get_beta`, ptr, step)
}

#' @title Get Cp scores from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of Cp scores
#' @noRd
tsolver_get_cp <- function(ptr) {
    .Call(`_TRexSelector_tsolver_get_cp`, ptr)
}

#' @title Get RSS from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of RSS scores
#' @noRd
tsolver_get_rss <- function(ptr) {
    .Call(`_TRexSelector_tsolver_get_rss`, ptr)
}

#' @title Get R2 from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of R2 scores
#' @noRd
tsolver_get_r2 <- function(ptr) {
    .Call(`_TRexSelector_tsolver_get_r2`, ptr)
}

#' @title Get Degrees of Freedom from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of DoF
#' @noRd
tsolver_get_dof <- function(ptr) {
    .Call(`_TRexSelector_tsolver_get_dof`, ptr)
}

#' @title Get Active Set from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of active variable indices
#' @noRd
tsolver_get_actives <- function(ptr) {
    .Call(`_TRexSelector_tsolver_get_actives`, ptr)
}

#' @title Get Inactive Set from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @return Numeric vector of inactive variable indices
#' @noRd
tsolver_get_inactives <- function(ptr) {
    .Call(`_TRexSelector_tsolver_get_inactives`, ptr)
}

#' @title Get Intercept from TSolver
#'
#' @param ptr TSolverRcpp holder pointer
#' @param step Step to retrieve the intercept for
#' @return Numeric intercept value
#' @noRd
tsolver_get_intercept <- function(ptr, step = -1L) {
    .Call(`_TRexSelector_tsolver_get_intercept`, ptr, step)
}

#' @noRd
tsolver_get_num_steps <- function(ptr) {
    .Call(`_TRexSelector_tsolver_get_num_steps`, ptr)
}

#' @noRd
tsolver_get_actions <- function(ptr) {
    .Call(`_TRexSelector_tsolver_get_actions`, ptr)
}

#' @noRd
tsolver_get_lambda <- function(ptr) {
    .Call(`_TRexSelector_tsolver_get_lambda`, ptr)
}

#' @noRd
tsolver_get_num_removals <- function(ptr) {
    .Call(`_TRexSelector_tsolver_get_num_removals`, ptr)
}

#' @noRd
tsolver_get_cycling_ratio <- function(ptr) {
    .Call(`_TRexSelector_tsolver_get_cycling_ratio`, ptr)
}

#' @title Save TSolver to File
#'
#' @param ptr TSolverRcpp holder pointer
#' @param filename Output filename
#' @noRd
tsolver_save <- function(ptr, filename) {
    invisible(.Call(`_TRexSelector_tsolver_save`, ptr, filename))
}

#' @title Load TSolver from File
#'
#' @param ptr TSolverRcpp holder pointer
#' @param filename Input filename
#' @noRd
tsolver_load <- function(ptr, filename) {
    invisible(.Call(`_TRexSelector_tsolver_load`, ptr, filename))
}

#' @title Set custom temp directory for the C++ backend
#'
#' @description Injects the R session's tempdir() into the C++ backend to obey CRAN memory rules.
#'
#' @param temp_dir The absolute path to the directory (e.g. from `tempdir()`).
#'
#' @noRd
rcpp_set_custom_temp_dir <- function(temp_dir) {
    invisible(.Call(`_TRexSelector_rcpp_set_custom_temp_dir`, temp_dir))
}

#' @title Create Memory Mapped Matrix
#'
#' @param filename Path to the file.
#' @param rows Number of rows
#' @param cols Number of columns.
#' @param mode_idx Mode index with 0: ReadOnly, 1: ReadWrite.
#'
#' @return XPtr to MemoryMappedMatrix
#'
#' @noRd
mmap_matrix_create <- function(filename, rows, cols, mode_idx = 1L) {
    .Call(`_TRexSelector_mmap_matrix_create`, filename, rows, cols, mode_idx)
}

#' @title Convert Memory Mapped Matrix to R Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#'
#' @return NumericMatrix
#'
#' @noRd
mmap_matrix_to_r_matrix <- function(ptr) {
    .Call(`_TRexSelector_mmap_matrix_to_r_matrix`, ptr)
}

#' @title Convert R Matrix to Memory Mapped Matrix
#'
#' @param mat R NumericMatrix
#' @param filename Output filename
#'
#' @noRd
convert_to_memory_mapped_matrix <- function(mat, filename) {
    invisible(.Call(`_TRexSelector_convert_to_memory_mapped_matrix`, mat, filename))
}

#' @title Get Number of Rows in Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#'
#' @return Integer number of rows
#'
#' @noRd
mmap_matrix_rows <- function(ptr) {
    .Call(`_TRexSelector_mmap_matrix_rows`, ptr)
}

#' @title Get Number of Columns in Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @return Integer number of columns
#'
#' @noRd
mmap_matrix_cols <- function(ptr) {
    .Call(`_TRexSelector_mmap_matrix_cols`, ptr)
}

#' @title Get Total Size of Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#'
#' @return Integer total size
#'
#' @noRd
mmap_matrix_size <- function(ptr) {
    .Call(`_TRexSelector_mmap_matrix_size`, ptr)
}

#' @title Read Block from Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @param row_start Start row index (0-based)
#' @param row_count Number of rows to read
#' @param col_start Start column index (0-based)
#' @param col_count Number of columns to read
#'
#' @return NumericMatrix block
#'
#' @noRd
mmap_matrix_read_range <- function(ptr, row_start, row_count, col_start, col_count) {
    .Call(`_TRexSelector_mmap_matrix_read_range`, ptr, row_start, row_count, col_start, col_count)
}

#' @title Compute FDP from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#'
#' @return FDP value
#'
#' @noRd
rcpp_compute_fdp <- function(selected_indices, true_support) {
    .Call(`_TRexSelector_rcpp_compute_fdp`, selected_indices, true_support)
}

#' @title Compute TPP from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#'
#' @return TPP value
#'
#' @noRd
rcpp_compute_tpp <- function(selected_indices, true_support) {
    .Call(`_TRexSelector_rcpp_compute_tpp`, selected_indices, true_support)
}

#' @title Compute Precision from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#'
#' @return Precision value
#'
#' @noRd
rcpp_compute_precision <- function(selected_indices, true_support) {
    .Call(`_TRexSelector_rcpp_compute_precision`, selected_indices, true_support)
}

#' @title Compute Recall from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#'
#' @return Recall value
#'
#' @noRd
rcpp_compute_recall <- function(selected_indices, true_support) {
    .Call(`_TRexSelector_rcpp_compute_recall`, selected_indices, true_support)
}

#' @title Compute FDP from dense vectors
#'
#' @param beta_hat Estimated coefficients.
#' @param beta True coefficients.
#' @param eps Tolerance.
#'
#' @return FDP value
#'
#' @noRd
rcpp_compute_fdp_dense <- function(beta_hat, beta, eps = 1e-15) {
    .Call(`_TRexSelector_rcpp_compute_fdp_dense`, beta_hat, beta, eps)
}

#' @title Compute TPP from dense vectors
#'
#' @param beta_hat Estimated coefficients.
#' @param beta True coefficients.
#' @param eps Tolerance.
#'
#' @return TPP value.
#'
#' @noRd
rcpp_compute_tpp_dense <- function(beta_hat, beta, eps = 1e-15) {
    .Call(`_TRexSelector_rcpp_compute_tpp_dense`, beta_hat, beta, eps)
}

