# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Rcpp Agglomerative Clustering
#'
#' @description Perform agglomerative clustering
#'
#' @param data Matrix of shape (N, Features).
#' @param method_idx Linkage method index (0=Ward, 1=Average, 2=Complete, 3=Single, 4=WPGMA,
#'                      5=Median, 6=Centroid)
#' @param metric_idx Distance metric index (0=Euclid, 1=Corr, 2=Manhattan, 3=CorrLSHF, 4=CorrLSHA)
#' @param use_mmap Boolean flag for memory mapping
#'
#' @return A linkage matrix
#' @noRd
rcpp_agglomerative_cluster <- function(data, method_idx, metric_idx, use_mmap = FALSE) {
    .Call('_TRexSelector_rcpp_agglomerative_cluster', PACKAGE = 'TRexSelector', data, method_idx, metric_idx, use_mmap)
}

#' @title Rcpp Cut Tree
#'
#' @description Cut a linkage matrix into flat clusters
#'
#' @param linkage Linkage matrix from agglomerative_cluster
#' @param num_orig_objs Original number of rows in dataset
#' @param num_clusters Desired number of flat clusters
#'
#' @return Integer vector of cluster indices
#' @noRd
rcpp_cut_tree <- function(linkage, num_orig_objs, num_clusters) {
    .Call('_TRexSelector_rcpp_cut_tree', PACKAGE = 'TRexSelector', linkage, num_orig_objs, num_clusters)
}

#' @title Create ZScoreScaler
#'
#' @param with_mean Center data
#' @param with_std Scale data
#' @return XPtr to ZScoreScaler
#' @noRd
zscore_scaler_create <- function(with_mean, with_std) {
    .Call('_TRexSelector_zscore_scaler_create', PACKAGE = 'TRexSelector', with_mean, with_std)
}

#' @title Fit ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param X Matrix to fit
#' @param threshold Numerical stability threshold
#' @noRd
zscore_scaler_fit <- function(ptr, X, threshold = 1e-12) {
    invisible(.Call('_TRexSelector_zscore_scaler_fit', PACKAGE = 'TRexSelector', ptr, X, threshold))
}

#' @title Transform Inplace ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param X Matrix to transform
#' @noRd
zscore_scaler_transform_inplace <- function(ptr, X) {
    invisible(.Call('_TRexSelector_zscore_scaler_transform_inplace', PACKAGE = 'TRexSelector', ptr, X))
}

#' @title Inverse Transform Inplace ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param X Matrix to transform
#' @noRd
zscore_scaler_inverse_transform_inplace <- function(ptr, X) {
    invisible(.Call('_TRexSelector_zscore_scaler_inverse_transform_inplace', PACKAGE = 'TRexSelector', ptr, X))
}

#' @title Check if ZScoreScaler is fitted
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Boolean indicating fit status
#' @noRd
zscore_scaler_is_fitted <- function(ptr) {
    .Call('_TRexSelector_zscore_scaler_is_fitted', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get dropped indices from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Vector of dropped indices
#' @noRd
zscore_scaler_get_dropped_indices <- function(ptr) {
    .Call('_TRexSelector_zscore_scaler_get_dropped_indices', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get with_mean flag from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Boolean with_mean
#' @noRd
zscore_scaler_get_with_mean <- function(ptr) {
    .Call('_TRexSelector_zscore_scaler_get_with_mean', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get with_std flag from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Boolean with_std
#' @noRd
zscore_scaler_get_with_std <- function(ptr) {
    .Call('_TRexSelector_zscore_scaler_get_with_std', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get means from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Vector of means
#' @noRd
zscore_scaler_get_means <- function(ptr) {
    .Call('_TRexSelector_zscore_scaler_get_means', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get scales from ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @return Vector of scales
#' @noRd
zscore_scaler_get_scales <- function(ptr) {
    .Call('_TRexSelector_zscore_scaler_get_scales', PACKAGE = 'TRexSelector', ptr)
}

#' @title Save ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param filename Output filename
#' @noRd
zscore_scaler_save <- function(ptr, filename) {
    invisible(.Call('_TRexSelector_zscore_scaler_save', PACKAGE = 'TRexSelector', ptr, filename))
}

#' @title Load ZScoreScaler
#'
#' @param ptr XPtr to ZScoreScaler
#' @param filename Input filename
#' @noRd
zscore_scaler_load <- function(ptr, filename) {
    invisible(.Call('_TRexSelector_zscore_scaler_load', PACKAGE = 'TRexSelector', ptr, filename))
}

#' @title Create LpNormScaler
#'
#' @param norm_type Type of norm (1 for L1, 2 for L2)
#' @param with_mean Center data
#' @return XPtr to LpNormScaler
#' @noRd
lpnorm_scaler_create <- function(norm_type, with_mean) {
    .Call('_TRexSelector_lpnorm_scaler_create', PACKAGE = 'TRexSelector', norm_type, with_mean)
}

#' @title Fit LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param X Matrix to fit
#' @param threshold Numerical stability threshold
#' @noRd
lpnorm_scaler_fit <- function(ptr, X, threshold = 1e-12) {
    invisible(.Call('_TRexSelector_lpnorm_scaler_fit', PACKAGE = 'TRexSelector', ptr, X, threshold))
}

#' @title Transform Inplace LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param X Matrix to transform
#' @noRd
lpnorm_scaler_transform_inplace <- function(ptr, X) {
    invisible(.Call('_TRexSelector_lpnorm_scaler_transform_inplace', PACKAGE = 'TRexSelector', ptr, X))
}

#' @title Inverse Transform Inplace LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param X Matrix to transform
#' @noRd
lpnorm_scaler_inverse_transform_inplace <- function(ptr, X) {
    invisible(.Call('_TRexSelector_lpnorm_scaler_inverse_transform_inplace', PACKAGE = 'TRexSelector', ptr, X))
}

#' @title Check if LpNormScaler is fitted
#'
#' @param ptr XPtr to LpNormScaler
#' @return Boolean indicating fit status
#' @noRd
lpnorm_scaler_is_fitted <- function(ptr) {
    .Call('_TRexSelector_lpnorm_scaler_is_fitted', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get dropped indices from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Vector of dropped indices
#' @noRd
lpnorm_scaler_get_dropped_indices <- function(ptr) {
    .Call('_TRexSelector_lpnorm_scaler_get_dropped_indices', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get means from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Vector of means
#' @noRd
lpnorm_scaler_get_means <- function(ptr) {
    .Call('_TRexSelector_lpnorm_scaler_get_means', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get scales from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Vector of scales
#' @noRd
lpnorm_scaler_get_scales <- function(ptr) {
    .Call('_TRexSelector_lpnorm_scaler_get_scales', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get with_mean flag from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Boolean with_mean
#' @noRd
lpnorm_scaler_get_with_mean <- function(ptr) {
    .Call('_TRexSelector_lpnorm_scaler_get_with_mean', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get with_norm flag from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Boolean with_norm
#' @noRd
lpnorm_scaler_get_with_norm <- function(ptr) {
    .Call('_TRexSelector_lpnorm_scaler_get_with_norm', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get norm type from LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @return Integer norm type
#' @noRd
lpnorm_scaler_get_norm_type <- function(ptr) {
    .Call('_TRexSelector_lpnorm_scaler_get_norm_type', PACKAGE = 'TRexSelector', ptr)
}

#' @title Save LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param filename Output filename
#' @noRd
lpnorm_scaler_save <- function(ptr, filename) {
    invisible(.Call('_TRexSelector_lpnorm_scaler_save', PACKAGE = 'TRexSelector', ptr, filename))
}

#' @title Load LpNormScaler
#'
#' @param ptr XPtr to LpNormScaler
#' @param filename Input filename
#' @noRd
lpnorm_scaler_load <- function(ptr, filename) {
    invisible(.Call('_TRexSelector_lpnorm_scaler_load', PACKAGE = 'TRexSelector', ptr, filename))
}

#' @title Create Ridge GCV
#'
#' @return XPtr to ridge_gcv
#' @noRd
ridge_gcv_create <- function() {
    .Call('_TRexSelector_ridge_gcv_create', PACKAGE = 'TRexSelector')
}

#' @title Fit Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param X Design matrix
#' @param y Response vector
#' @noRd
ridge_gcv_fit <- function(ptr, X, y) {
    invisible(.Call('_TRexSelector_ridge_gcv_fit', PACKAGE = 'TRexSelector', ptr, X, y))
}

#' @title Solve Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param lambda_val Lambda value
#' @return Coefficients
#' @noRd
ridge_gcv_solve <- function(ptr, lambda_val) {
    .Call('_TRexSelector_ridge_gcv_solve', PACKAGE = 'TRexSelector', ptr, lambda_val)
}

#' @title Get GCV Score
#'
#' @param ptr XPtr to ridge_gcv
#' @param lambda_val Lambda value
#' @return GCV score
#' @noRd
ridge_gcv_gcv_score <- function(ptr, lambda_val) {
    .Call('_TRexSelector_ridge_gcv_gcv_score', PACKAGE = 'TRexSelector', ptr, lambda_val)
}

#' @title Predict with Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param X_new New data
#' @param lambda_val Lambda value
#' @return Predictions
#' @noRd
ridge_gcv_predict <- function(ptr, X_new, lambda_val) {
    .Call('_TRexSelector_ridge_gcv_predict', PACKAGE = 'TRexSelector', ptr, X_new, lambda_val)
}

#' @title Predict Path with Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param X_new New data
#' @param lambdas Lambda values
#' @return Predictions
#' @noRd
ridge_gcv_predict_path <- function(ptr, X_new, lambdas) {
    .Call('_TRexSelector_ridge_gcv_predict_path', PACKAGE = 'TRexSelector', ptr, X_new, lambdas)
}

#' @title Get Default Lambda Grid from Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param num_lambda Number of lambdas
#' @param ratio Ratio
#' @return Lambda grid
#' @noRd
ridge_gcv_default_lambda_grid <- function(ptr, num_lambda, ratio) {
    .Call('_TRexSelector_ridge_gcv_default_lambda_grid', PACKAGE = 'TRexSelector', ptr, num_lambda, ratio)
}

#' @title Get number of samples from Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @return Number of samples
#' @noRd
ridge_gcv_n_samples <- function(ptr) {
    .Call('_TRexSelector_ridge_gcv_n_samples', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get number of features from Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @return Number of features
#' @noRd
ridge_gcv_n_features <- function(ptr) {
    .Call('_TRexSelector_ridge_gcv_n_features', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get rank from Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @return Rank
#' @noRd
ridge_gcv_rank <- function(ptr) {
    .Call('_TRexSelector_ridge_gcv_rank', PACKAGE = 'TRexSelector', ptr)
}

#' @title Solve Path Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param lambdas Lambda values
#' @return List of path results
#' @noRd
ridge_gcv_solve_path <- function(ptr, lambdas) {
    .Call('_TRexSelector_ridge_gcv_solve_path', PACKAGE = 'TRexSelector', ptr, lambdas)
}

#' @title Get optimal lambda from Ridge GCV
#'
#' @param ptr XPtr to ridge_gcv
#' @param num_grid Number of grid points
#' @param tol Tolerance
#' @return Optimal GCV lambda
#' @noRd
ridge_gcv_optimal <- function(ptr, num_grid, tol) {
    .Call('_TRexSelector_ridge_gcv_optimal', PACKAGE = 'TRexSelector', ptr, num_grid, tol)
}

#' @title Create Ridge CV
#'
#' @return XPtr to ridge_cv
#' @noRd
ridge_cv_create <- function() {
    .Call('_TRexSelector_ridge_cv_create', PACKAGE = 'TRexSelector')
}

#' @title Fit Ridge CV
#'
#' @param ptr XPtr to ridge_cv
#' @param X Design matrix
#' @param y Response vector
#' @param num_folds Number of folds
#' @param n_lambda Number of lambdas
#' @param lambda_ratio Lambda ratio
#' @param seed Random seed
#' @noRd
ridge_cv_fit <- function(ptr, X, y, num_folds, n_lambda, lambda_ratio, seed) {
    invisible(.Call('_TRexSelector_ridge_cv_fit', PACKAGE = 'TRexSelector', ptr, X, y, num_folds, n_lambda, lambda_ratio, seed))
}

#' @title Get min CV error
#'
#' @param ptr XPtr to ridge_cv
#' @return Min CV error
#' @noRd
ridge_cv_min <- function(ptr) {
    .Call('_TRexSelector_ridge_cv_min', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get 1SE CV error
#'
#' @param ptr XPtr to ridge_cv
#' @return 1SE CV error
#' @noRd
ridge_cv_1se <- function(ptr) {
    .Call('_TRexSelector_ridge_cv_1se', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get min index
#'
#' @param ptr XPtr to ridge_cv
#' @return Index of min CV error
#' @noRd
ridge_cv_index_min <- function(ptr) {
    .Call('_TRexSelector_ridge_cv_index_min', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get 1SE index
#'
#' @param ptr XPtr to ridge_cv
#' @return Index of 1SE CV error
#' @noRd
ridge_cv_index_1se <- function(ptr) {
    .Call('_TRexSelector_ridge_cv_index_1se', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get Lambdas
#'
#' @param ptr XPtr to ridge_cv
#' @return Vector of lambdas
#' @noRd
ridge_cv_get_lambdas <- function(ptr) {
    .Call('_TRexSelector_ridge_cv_get_lambdas', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get CV Errors
#'
#' @param ptr XPtr to ridge_cv
#' @return Vector of CV errors
#' @noRd
ridge_cv_get_cv_errors <- function(ptr) {
    .Call('_TRexSelector_ridge_cv_get_cv_errors', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get CV Standard Errors
#'
#' @param ptr XPtr to ridge_cv
#' @return Vector of CV standard errors
#' @noRd
ridge_cv_get_cv_std <- function(ptr) {
    .Call('_TRexSelector_ridge_cv_get_cv_std', PACKAGE = 'TRexSelector', ptr)
}

#' @title Create TRexSelector
#' @noRd
trex_selector_create <- function(X, y, tFDR, control_list, seed, verbose) {
    .Call('_TRexSelector_trex_selector_create', PACKAGE = 'TRexSelector', X, y, tFDR, control_list, seed, verbose)
}

#' @title Create TRexSelector from mmap
#' @noRd
trex_selector_mmap_create <- function(X_ptr, y, tFDR, control_list, seed, verbose) {
    .Call('_TRexSelector_trex_selector_mmap_create', PACKAGE = 'TRexSelector', X_ptr, y, tFDR, control_list, seed, verbose)
}

#' @title Run TRexSelector
#' @noRd
trex_selector_select <- function(r_ptr) {
    .Call('_TRexSelector_trex_selector_select', PACKAGE = 'TRexSelector', r_ptr)
}

#' @title Get Selected Indices
#' @noRd
trex_selector_get_selected_indices <- function(r_ptr) {
    .Call('_TRexSelector_trex_selector_get_selected_indices', PACKAGE = 'TRexSelector', r_ptr)
}

#' @title Create TRexDASelector
#' @noRd
trex_da_create <- function(X, y, tFDR, da_control_list, trex_control_list, seed, verbose) {
    .Call('_TRexSelector_trex_da_create', PACKAGE = 'TRexSelector', X, y, tFDR, da_control_list, trex_control_list, seed, verbose)
}

#' @title Create TRexDASelector from mmap
#' @noRd
trex_da_mmap_create <- function(X_ptr, y, tFDR, da_control_list, trex_control_list, seed, verbose) {
    .Call('_TRexSelector_trex_da_mmap_create', PACKAGE = 'TRexSelector', X_ptr, y, tFDR, da_control_list, trex_control_list, seed, verbose)
}

#' @title Run TRexDASelector
#' @noRd
trex_da_select <- function(r_ptr) {
    .Call('_TRexSelector_trex_da_select', PACKAGE = 'TRexSelector', r_ptr)
}

#' @title Get Selected Indices for DA
#' @noRd
trex_da_get_selected_indices <- function(r_ptr) {
    .Call('_TRexSelector_trex_da_get_selected_indices', PACKAGE = 'TRexSelector', r_ptr)
}

#' @title Create LARS Solver
#'
#' @param X Design matrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolver_Base
#' @noRd
tsolver_lars_create <- function(X, D, y) {
    .Call('_TRexSelector_tsolver_lars_create', PACKAGE = 'TRexSelector', X, D, y)
}

#' @title Create OMP Solver
#'
#' @param X Design matrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolver_Base
#' @noRd
tsolver_omp_create <- function(X, D, y) {
    .Call('_TRexSelector_tsolver_omp_create', PACKAGE = 'TRexSelector', X, D, y)
}

#' @title Create LARS Solver with Memory Mapped Matrix
#'
#' @param X_ptr Pointer to MemoryMappedMatrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolver_Base
#' @noRd
tsolver_lars_mmap_create <- function(X_ptr, D, y) {
    .Call('_TRexSelector_tsolver_lars_mmap_create', PACKAGE = 'TRexSelector', X_ptr, D, y)
}

#' @title Create OMP Solver with Memory Mapped Matrix
#'
#' @param X_ptr Pointer to MemoryMappedMatrix
#' @param D Dummy matrix
#' @param y Response vector
#'
#' @return XPtr to TSolver_Base
#' @noRd
tsolver_omp_mmap_create <- function(X_ptr, D, y) {
    .Call('_TRexSelector_tsolver_omp_mmap_create', PACKAGE = 'TRexSelector', X_ptr, D, y)
}

#' @title Execute Step in TSolver
#'
#' @param ptr TSolver_Base instance pointer
#' @param T_stop Number of steps to compute
#' @param early_stop Whether to stop early based on constraints
#' @noRd
tsolver_execute_step <- function(ptr, T_stop, early_stop = TRUE) {
    invisible(.Call('_TRexSelector_tsolver_execute_step', PACKAGE = 'TRexSelector', ptr, T_stop, early_stop))
}

#' @title Get Beta from TSolver
#'
#' @param ptr TSolver_Base instance pointer
#' @param step Step to retrieve beta for
#'
#' @return Beta vector
#' @noRd
tsolver_get_beta <- function(ptr, step = -1L) {
    .Call('_TRexSelector_tsolver_get_beta', PACKAGE = 'TRexSelector', ptr, step)
}

#' @title Get Cp scores from TSolver
#'
#' @param ptr TSolver_Base instance pointer
#' @return Numeric vector of Cp scores
#' @noRd
tsolver_get_cp <- function(ptr) {
    .Call('_TRexSelector_tsolver_get_cp', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get RSS from TSolver
#'
#' @param ptr TSolver_Base instance pointer
#' @return Numeric vector of RSS scores
#' @noRd
tsolver_get_rss <- function(ptr) {
    .Call('_TRexSelector_tsolver_get_rss', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get R2 from TSolver
#'
#' @param ptr TSolver_Base instance pointer
#' @return Numeric vector of R2 scores
#' @noRd
tsolver_get_r2 <- function(ptr) {
    .Call('_TRexSelector_tsolver_get_r2', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get Degrees of Freedom from TSolver
#'
#' @param ptr TSolver_Base instance pointer
#' @return Numeric vector of DoF
#' @noRd
tsolver_get_dof <- function(ptr) {
    .Call('_TRexSelector_tsolver_get_dof', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get Active Set from TSolver
#'
#' @param ptr TSolver_Base instance pointer
#' @return Numeric vector of active variable indices
#' @noRd
tsolver_get_actives <- function(ptr) {
    .Call('_TRexSelector_tsolver_get_actives', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get Inactive Set from TSolver
#'
#' @param ptr TSolver_Base instance pointer
#' @return Numeric vector of inactive variable indices
#' @noRd
tsolver_get_inactives <- function(ptr) {
    .Call('_TRexSelector_tsolver_get_inactives', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get Intercept from TSolver
#'
#' @param ptr TSolver_Base instance pointer
#' @param step Step to retrieve the intercept for
#' @return Numeric intercept value
#' @noRd
tsolver_get_intercept <- function(ptr, step = -1L) {
    .Call('_TRexSelector_tsolver_get_intercept', PACKAGE = 'TRexSelector', ptr, step)
}

#' @title Save TSolver to File
#'
#' @param ptr TSolver_Base instance pointer
#' @param filename Output filename
#' @noRd
tsolver_save <- function(ptr, filename) {
    invisible(.Call('_TRexSelector_tsolver_save', PACKAGE = 'TRexSelector', ptr, filename))
}

#' @title Load TSolver from File
#'
#' @param ptr TSolver_Base instance pointer
#' @param filename Input filename
#' @noRd
tsolver_load <- function(ptr, filename) {
    invisible(.Call('_TRexSelector_tsolver_load', PACKAGE = 'TRexSelector', ptr, filename))
}

#' @title Create Memory Mapped Matrix
#'
#' @param filename Path to the file
#' @param rows Number of rows
#' @param cols Number of columns
#' @param mode_idx Mode index
#' @return XPtr to MemoryMappedMatrix
#' @noRd
mmap_matrix_create <- function(filename, rows, cols, mode_idx = 1L) {
    .Call('_TRexSelector_mmap_matrix_create', PACKAGE = 'TRexSelector', filename, rows, cols, mode_idx)
}

#' @title Convert Memory Mapped Matrix to R Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @return NumericMatrix
#' @noRd
mmap_matrix_to_r_matrix <- function(ptr) {
    .Call('_TRexSelector_mmap_matrix_to_r_matrix', PACKAGE = 'TRexSelector', ptr)
}

#' @title Convert R Matrix to Memory Mapped Matrix
#'
#' @param mat R NumericMatrix
#' @param filename Output filename
#' @noRd
convert_to_memory_mapped_matrix <- function(mat, filename) {
    invisible(.Call('_TRexSelector_convert_to_memory_mapped_matrix', PACKAGE = 'TRexSelector', mat, filename))
}

#' @title Get Number of Rows in Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @return Integer number of rows
#' @noRd
mmap_matrix_rows <- function(ptr) {
    .Call('_TRexSelector_mmap_matrix_rows', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get Number of Columns in Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @return Integer number of columns
#' @noRd
mmap_matrix_cols <- function(ptr) {
    .Call('_TRexSelector_mmap_matrix_cols', PACKAGE = 'TRexSelector', ptr)
}

#' @title Get Total Size of Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @return Integer total size
#' @noRd
mmap_matrix_size <- function(ptr) {
    .Call('_TRexSelector_mmap_matrix_size', PACKAGE = 'TRexSelector', ptr)
}

#' @title Read Block from Memory Mapped Matrix
#'
#' @param ptr XPtr to MemoryMappedMatrix
#' @param row_start Start row index (0-based)
#' @param row_count Number of rows to read
#' @param col_start Start column index (0-based)
#' @param col_count Number of columns to read
#' @return NumericMatrix block
#' @noRd
mmap_matrix_read_range <- function(ptr, row_start, row_count, col_start, col_count) {
    .Call('_TRexSelector_mmap_matrix_read_range', PACKAGE = 'TRexSelector', ptr, row_start, row_count, col_start, col_count)
}

#' @title Compute FDP from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#' @return FDP value
#' @noRd
rcpp_compute_fdp <- function(selected_indices, true_support) {
    .Call('_TRexSelector_rcpp_compute_fdp', PACKAGE = 'TRexSelector', selected_indices, true_support)
}

#' @title Compute TPP from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#' @return TPP value
#' @noRd
rcpp_compute_tpp <- function(selected_indices, true_support) {
    .Call('_TRexSelector_rcpp_compute_tpp', PACKAGE = 'TRexSelector', selected_indices, true_support)
}

#' @title Compute Precision from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#' @return Precision value
#' @noRd
rcpp_compute_precision <- function(selected_indices, true_support) {
    .Call('_TRexSelector_rcpp_compute_precision', PACKAGE = 'TRexSelector', selected_indices, true_support)
}

#' @title Compute Recall from sets
#'
#' @param selected_indices Selected indices
#' @param true_support True support indices
#' @return Recall value
#' @noRd
rcpp_compute_recall <- function(selected_indices, true_support) {
    .Call('_TRexSelector_rcpp_compute_recall', PACKAGE = 'TRexSelector', selected_indices, true_support)
}

#' @title Compute FDP from dense vectors
#'
#' @param beta_hat Estimated coefficients
#' @param beta True coefficients
#' @param eps Tolerance
#' @return FDP value
#' @noRd
rcpp_compute_fdp_dense <- function(beta_hat, beta, eps = 1e-15) {
    .Call('_TRexSelector_rcpp_compute_fdp_dense', PACKAGE = 'TRexSelector', beta_hat, beta, eps)
}

#' @title Compute TPP from dense vectors
#'
#' @param beta_hat Estimated coefficients
#' @param beta True coefficients
#' @param eps Tolerance
#' @return TPP value
#' @noRd
rcpp_compute_tpp_dense <- function(beta_hat, beta, eps = 1e-15) {
    .Call('_TRexSelector_rcpp_compute_tpp_dense', PACKAGE = 'TRexSelector', beta_hat, beta, eps)
}

